In [1]:
# pip install selenium

### Selenium requires a webDriver to interface with the browser. 
<p>chromDriver for chrome</P>
<p>geckoDriver for Firefox</p>
<p>edgeDriver for Edge</p>

In [2]:
from selenium import webdriver 
# importing the web driver

from selenium.webdriver.chrome.service import Service 
#importing the service depending on the browser

from selenium.webdriver.common.by import By

import pandas as pd

In [3]:
service = Service(executable_path = "C:/Users/HP/Downloads/chromedriver-win64/chromedriver-win64/chromedriver.exe")
driver = webdriver.Chrome(service = service)
url = 'https://jiji.ng/vehicles'
driver.get(url)

In [4]:
driver

In [5]:
# Finding one element

item_col = driver.find_element(By.CLASS_NAME, 'masonry-column')
item = item_col.find_element(By.CLASS_NAME, 'masonry-item')
product_name = item.find_element(By.CLASS_NAME, 'qa-advert-title').text
product_price = item.find_element(By.CLASS_NAME, 'qa-advert-price').text
product_description = item.find_element(By.CLASS_NAME, 'b-list-advert-base__description-text').text
product_location = item.find_element(By.CLASS_NAME, 'b-list-advert__region__text').text
product_grade = item.find_element(By.CLASS_NAME, 'b-list-advert-base__item-attr').text
product_img = item.find_element(By.TAG_NAME,'img')

In [6]:
product_grade

'Brand New'

In [7]:
service = Service(executable_path = "C:/Users/HP/Downloads/chromedriver-win64/chromedriver-win64/chromedriver.exe")
driver = webdriver.Chrome(service = service)
url = 'https://jiji.ng/vehicles'
driver.get(url)

jiji_data = []

item_col = driver.find_elements(By.CLASS_NAME, 'masonry-column')

for item in item_col:
    goods = item.find_elements(By.CLASS_NAME, 'masonry-item')
    for good in goods:
        product_name = good.find_element(By.CLASS_NAME, 'qa-advert-title')
        name = product_name.text.strip() if product_name else 'NA'

        product_price = good.find_element(By.CLASS_NAME, 'qa-advert-price')
        price = product_price.text.strip() if product_price else 'NA'
        
        product_description = good.find_element(By.CLASS_NAME, 'b-list-advert-base__description-text')
        description = product_description.text.strip() if product_description else 'NA'
        
        product_location = good.find_element(By.CLASS_NAME, 'b-list-advert__region__text')
        location = product_location.text.strip() if product_location else 'NA'
        
        product_img = good.find_element(By.TAG_NAME,'img')
        image = product_img.get_attribute('src') if product_img else 'NA'

        try:
            product_grade = good.find_element(By.CLASS_NAME, 'b-list-advert-base__item-attr')
            grade = product_grade.text.strip() if product_grade else 'NA'
        except:
            grade = 'NA'

        product = {
            'Name': name,
            'Price': price,
            'Description': description,
            'Image_Link': image,
            'Location': location,
            'Grade': grade
        }
        jiji_data.append(product)
driver.quit() 
#always quit the driver

In [8]:
jiji_data

[{'Name': 'Hilux 2025 Upgrade Kit',
  'Price': '₦ 950,000',
  'Description': 'Hilux 2025 revo upgrade kit',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/169795695_MzAwLTIyNi1hNjVlMmViY2Fk.webp',
  'Location': 'Lagos, Mushin',
  'Grade': 'Brand New'},
 {'Name': 'Mercedes-Benz G-Class G 63 AMG 4MATIC 2020 Green',
  'Price': '₦ 340,000,000',
  'Description': 'Just landed MB G63 AmG Super Engine and Gear Immaculate Black interior Low mileage New entry...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/178117441_MzAwLTQwMC01ODk0OTgyMGEz.webp',
  'Location': 'Lagos, Lekki',
  'Grade': 'Foreign Used'},
 {'Name': 'Mercedes-Benz GLC-Class 2020 Gray',
  'Price': '₦ 48,500,000',
  'Description': 'Clean foreign used mercedes benz glc300 4matic 2020, nothing to fix everything is working properly',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/175076821_MzAwLTE2OS1kNzQyNWRjYWE5LTE.webp',
  'Location': 'Lagos, Amuwo-Odofin',
  'Grade': 'Foreign Used'},
 {'Name': 'Dm for Front Windscreen Glass Toyota,Lexus,Mercedes All Type',
  'Price': '₦ 60,000',
  'Description': 'Welcome to U.C global enterprises.Auto part n interiors.we specialized on Toyota and Lexus upgrade...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/161117551_MzAwLTQwMC0zMmM2ZTViZjcw.webp',
  'Location': 'Lagos, Mushin',
  'Grade': 'Brand New'},
 {'Name': 'Suzuki GSX 2018 Blue',
  'Price': '₦ 8,500,000',
  'Description': 'Suzuki gsx-1000r 1000cc 2018 model free helmet price:#8.5m naira(confirm price before purchase,...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/173538911_MzAwLTQwMC0wNDAxOTJiMDI1.webp',
  'Location': 'Osun, Ife',
  'Grade': 'Foreign Used'},
 {'Name': 'WD 40 Anti Rust Company Lagos Branch',
  'Price': '₦ 6,500',
  'Description': 'WD 40 penitreting oil Lagos Aspamda trade fair branch',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/146221004_MzAwLTIyNS04OTBhMGI3MzMzLTE.webp',
  'Location': 'Lagos, Ojo',
  'Grade': 'Bulk prices'},
 {'Name': 'Nissan Rogue Steering Wheel and Airbag.',
  'Price': '₦ 50,000',
  'Description': 'We are here to give you the best of car parts and accessories of all cars, and upgrade / conversion...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/97259094_MzAwLTIyNS03Yjg0ZDEyODRmLTE.webp',
  'Location': 'Lagos, Mushin',
  'Grade': 'Used'},
 {'Name': 'Steering Horn Control for Corolla 2005',
  'Price': '₦ 10,000',
  'Description': 'If your horn don’t blow again contact me on090*********',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/98361431_MzAwLTIyNS04MTMzMGFjYjk1LTE.webp',
  'Location': 'Lagos, Mushin',
  'Grade': 'Used'},
 {'Name': 'Shock Absorber Pad for All Motor',
  'Price': '₦ 30,000',
  'Description': 'Original shock absorber pad made from good Thailand quality (high standard)',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/30499868_20190607-121243_300x300.jpg',
  'Location': 'Lagos',
  'Grade': 'Brand New'},
 {'Name': 'Original Bushing For All Cars',
  'Price': '₦ 4,000',
  'Description': 'Original bushing for your lower arm and your stabilizer linkage rubber. The best you can trust for...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/35821478_20191014-165128_300x169.jpg',
  'Location': 'Lagos',
  'Grade': 'Brand New'},
 {'Name': 'Dm for Front Windscreen Is 250 2010 Available Now',
  'Price': '₦ 80,000',
  'Description': 'Welcome to U.C global enterprises.Auto part n interiors.we specialized on Toyota and Lexus upgrade...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/157866214_MzAwLTEzOC1lZWVhMTk1NTk3.webp',
  'Location': 'Lagos, Mushin',
  'Grade': 'Brand New'},
 {'Name': 'Abro Silicon 2000 Clear- White Black',
  'Price': '₦ 4,000',
  'Description': 'Abro 2000 clear silicone black and white',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/129678441_MzAwLTQ2OC1iMzRlNTEyNGE0LTE.webp',
  'Location': 'Lagos, Ojo',
  'Grade': 'Bulk prices'},
 {'Name': 'Honda Spare Parts',
  'Price': '₦ 7,500',
  'Description': 'We deal on honda spare parts such as direct tokumbo complete hubs, shocks, steering racks, complete...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/51935035_img-1599139783028_300x300.webp',
  'Location': 'Abuja, Apo District',
  'Grade': 'Used'},
 {'Name': 'Honda Driving Shaft, Shucks, Hub Bearing Steering Rack, ETC',
  'Price': '₦ 15,000',
  'Description': 'We sale all types of Honda spare parts Such as Accord, Civic, CRV, Pilot ETC',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/109511511_MzAwLTQwMC0zYjVjNDFhNzdj.webp',
  'Location': 'Abuja, Apo District',
  'Grade': 'Used'},
 {'Name': '2gr Engine for Toyota Camry 2012 V6',
  'Price': '₦ 1,200,000',
  'Description': 'Direct tokumbo with 2months guarantee',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/171981766_MzAwLTQzMi04MDY0ZTgzNTdi.webp',
  'Location': 'Lagos, Mushin',
  'Grade': 'Used'},
 {'Name': 'Universal Android Screen',
  'Price': '₦ 85,000',
  'Description': 'Android screen plug and play with Bluetooth reverse camera enabled, connect with your android device...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/132891787_MzAwLTIyMS1lOTM1Zjk4N2Vk.webp',
  'Location': 'Lagos, Ojo',
  'Grade': 'Brand New'},
 {'Name': 'Hub Bearing for All Cars (Japan Standard)',
  'Price': '₦ 35,000',
  'Description': 'Original complete hub bearing for all cars available at an affordable rate comes with two years...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/41652142_20200219-162342_300x225.jpg',
  'Location': 'Lagos',
  'Grade': 'Brand New'},
 {'Name': 'Gx470 Converted to Prado 2020 Model',
  'Price': '₦ 1,600,000',
  'Description': 'Rim. Tyar. Front and back light',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/168986433_MzAwLTQwMC0wODAyYjA2MTc3.webp',
  'Location': 'Lagos, Mushin',
  'Grade': 'Brand New'},
 {'Name': 'Upgrade Kit for Mercedes Gl450 2008 to 2018 Available',
  'Price': '₦ 8,000,000',
  'Description': 'Welcome to U.C global enterprises.Auto part n interiors.we specialized on Toyota and Lexus upgrade...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/162011021_MzAwLTQwMC1iY2JmNDY0MDBl.webp',
  'Location': 'Lagos, Mushin',
  'Grade': 'Brand New'},
 {'Name': 'Upgrade Your Mercedes G Wagon 2025 Model',
  'Price': '₦ 28,000,000',
  'Description': 'Upgrade your Mercedes Benz G wagon 2025 model made in Germany with one year guarantee delivery...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/170650055_MzAwLTM3MS1jNGJkNjg0MDJk.webp',
  'Location': 'Lagos, Mushin',
  'Grade': 'Brand New'},
 {'Name': 'New Tires With Good Qualities',
  'Price': '₦ 65,000',
  'Description': 'I Sale All types of motor Tires, New one or Belgium one, with Good price',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/135497823_MzAwLTQwMC1mNmFmN2UxOTcz.webp',
  'Location': 'Abuja, Apo District',
  'Grade': 'Brand New'},
 {'Name': 'Auto Base 1kg Pure White Paint',
  'Price': '₦ 12,500',
  'Description': 'Auto base 1kg pure white paint',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/158433253_MzAwLTM5OC1mMmMzOTY4MzhlLTE.webp',
  'Location': 'Lagos, Ojo',
  'Grade': 'Brand New'},
 {'Name': 'Gearbox Toyota Camry 2004 Model Direct Tokunbo',
  'Price': '₦ 600,000',
  'Description': 'Gearbox Toyota camry 2004 model is available as you seen very neet direct tokunbo',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/174067450_MzAwLTQwMC04YmUwOTI3ZWFk.webp',
  'Location': 'Lagos, Mushin',
  'Grade': 'Used'},
 {'Name': 'All Kind of Mercedes-Benz Headlight Light',
  'Price': '₦ 20,000',
  'Description': 'Available now for sale',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/151128730_MzAwLTEzNS0xMmFjMjZiZTRh.webp',
  'Location': 'Lagos, Mushin',
  'Grade': 'Brand New'}]

In [9]:
df = pd.DataFrame(jiji_data)
df

,Name,Price,Description,Image_Link,Location,Grade
0,Hilux 2025 Upgrade Kit,"₦ 950,000",Hilux 2025 revo upgrade kit,https://pictures-nigeria.jijistatic.net/169795...,"Lagos, Mushin",Brand New
1,Mercedes-Benz G-Class G 63 AMG 4MATIC 2020 Green,"₦ 340,000,000",Just landed MB G63 AmG Super Engine and Gear I...,https://pictures-nigeria.jijistatic.net/178117...,"Lagos, Lekki",Foreign Used
2,Mercedes-Benz GLC-Class 2020 Gray,"₦ 48,500,000",Clean foreign used mercedes benz glc300 4matic...,https://pictures-nigeria.jijistatic.net/175076...,"Lagos, Amuwo-Odofin",Foreign Used
3,"Dm for Front Windscreen Glass Toyota,Lexus,Mer...","₦ 60,000",Welcome to U.C global enterprises.Auto part n ...,https://pictures-nigeria.jijistatic.net/161117...,"Lagos, Mushin",Brand New
4,Suzuki GSX 2018 Blue,"₦ 8,500,000",Suzuki gsx-1000r 1000cc 2018 model free helmet...,https://pictures-nigeria.jijistatic.net/173538...,"Osun, Ife",Foreign Used
5,WD 40 Anti Rust Company Lagos Branch,"₦ 6,500",WD 40 penitreting oil Lagos Aspamda trade fair...,https://pictures-nigeria.jijistatic.net/146221...,"Lagos, Ojo",Bulk prices
6,Nissan Rogue Steering Wheel and Airbag.,"₦ 50,000",We are here to give you the best of car parts ...,https://pictures-nigeria.jijistatic.net/972590...,"Lagos, Mushin",Used
7,Steering Horn Control for Corolla 2005,"₦ 10,000",If your horn don’t blow again contact me on090...,https://pictures-nigeria.jijistatic.net/983614...,"Lagos, Mushin",Used
8,Shock Absorber Pad for All Motor,"₦ 30,000",Original shock absorber pad made from good Tha...,https://pictures-nigeria.jijistatic.net/304998...,Lagos,Brand New
9,Original Bushing For All Cars,"₦ 4,000",Original bushing for your lower arm and your s...,https://pictures-nigeria.jijistatic.net/358214...,Lagos,Brand New
10,Dm for Front Windscreen Is 250 2010 Available Now,"₦ 80,000",Welcome to U.C global enterprises.Auto part n ...,https://pictures-nigeria.jijistatic.net/157866...,"Lagos, Mushin",Brand New
11,Abro Silicon 2000 Clear- White Black,"₦ 4,000",Abro 2000 clear silicone black and white,https://pictures-nigeria.jijistatic.net/129678...,"Lagos, Ojo",Bulk prices
12,Honda Spare Parts,"₦ 7,500",We deal on honda spare parts such as direct to...,https://pictures-nigeria.jijistatic.net/519350...,"Abuja, Apo District",Used
13,"Honda Driving Shaft, Shucks, Hub Bearing Steer...","₦ 15,000",We sale all types of Honda spare parts Such as...,https://pictures-nigeria.jijistatic.net/109511...,"Abuja, Apo District",Used
14,2gr Engine for Toyota Camry 2012 V6,"₦ 1,200,000",Direct tokumbo with 2months guarantee,https://pictures-nigeria.jijistatic.net/171981...,"Lagos, Mushin",Used
15,Universal Android Screen,"₦ 85,000",Android screen plug and play with Bluetooth re...,https://pictures-nigeria.jijistatic.net/132891...,"Lagos, Ojo",Brand New
16,Hub Bearing for All Cars (Japan Standard),"₦ 35,000",Original complete hub bearing for all cars ava...,https://pictures-nigeria.jijistatic.net/416521...,Lagos,Brand New
17,Gx470 Converted to Prado 2020 Model,"₦ 1,600,000",Rim. Tyar. Front and back light,https://pictures-nigeria.jijistatic.net/168986...,"Lagos, Mushin",Brand New
18,Upgrade Kit for Mercedes Gl450 2008 to 2018 Av...,"₦ 8,000,000",Welcome to U.C global enterprises.Auto part n ...,https://pictures-nigeria.jijistatic.net/162011...,"Lagos, Mushin",Brand New
19,Upgrade Your Mercedes G Wagon 2025 Model,"₦ 28,000,000",Upgrade your Mercedes Benz G wagon 2025 model ...,https://pictures-nigeria.jijistatic.net/170650...,"Lagos, Mushin",Brand New
20,New Tires With Good Qualities,"₦ 65,000","I Sale All types of motor Tires, New one or Be...",https://pictures-nigeria.jijistatic.net/135497...,"Abuja, Apo District",Brand New
21,Auto Base 1kg Pure White Paint,"₦ 12,500",Auto base 1kg pure white paint,https://pictures-nigeria.jijistatic.net/158433...,"Lagos, Ojo",Brand New
22,Gearbox Toyota Camry 2004 Model Direct Tokunbo,"₦ 600,000",Gearbox Toyota camry 2004 model is available a...,https://pictures-nigeria.jijistatic.net/174067...,"Lagos, Mushin",Used
23,All Kind of Mercedes-Benz Headlight Light,"₦ 20,000",Available now for sale,https://pictures-nigeria.jijistatic.net/151128...,"Lagos, Mushin",Brand New

In [10]:
df.dtypes

Name           object
Price          object
Description    object
Image_Link     object
Location       object
Grade          object
dtype: object

In [11]:
df['Sellingprice'] = df['Price'].astype(str).replace(r'[^\d.]', '',regex =True).astype(float) 
#first converted to string, then replaced, and re converted to float
# r'[^\d.]', '',regex =True removes any non-numerical value and replace with nothing

#Then assign selling price to Price + 20%
df['Sellingprice'] = df['Sellingprice'] + (0.2 * df['Sellingprice'])
df

,Name,Price,Description,Image_Link,Location,Grade,Sellingprice
0,Hilux 2025 Upgrade Kit,"₦ 950,000",Hilux 2025 revo upgrade kit,https://pictures-nigeria.jijistatic.net/169795...,"Lagos, Mushin",Brand New,1140000.0
1,Mercedes-Benz G-Class G 63 AMG 4MATIC 2020 Green,"₦ 340,000,000",Just landed MB G63 AmG Super Engine and Gear I...,https://pictures-nigeria.jijistatic.net/178117...,"Lagos, Lekki",Foreign Used,408000000.0
2,Mercedes-Benz GLC-Class 2020 Gray,"₦ 48,500,000",Clean foreign used mercedes benz glc300 4matic...,https://pictures-nigeria.jijistatic.net/175076...,"Lagos, Amuwo-Odofin",Foreign Used,58200000.0
3,"Dm for Front Windscreen Glass Toyota,Lexus,Mer...","₦ 60,000",Welcome to U.C global enterprises.Auto part n ...,https://pictures-nigeria.jijistatic.net/161117...,"Lagos, Mushin",Brand New,72000.0
4,Suzuki GSX 2018 Blue,"₦ 8,500,000",Suzuki gsx-1000r 1000cc 2018 model free helmet...,https://pictures-nigeria.jijistatic.net/173538...,"Osun, Ife",Foreign Used,10200000.0
5,WD 40 Anti Rust Company Lagos Branch,"₦ 6,500",WD 40 penitreting oil Lagos Aspamda trade fair...,https://pictures-nigeria.jijistatic.net/146221...,"Lagos, Ojo",Bulk prices,7800.0
6,Nissan Rogue Steering Wheel and Airbag.,"₦ 50,000",We are here to give you the best of car parts ...,https://pictures-nigeria.jijistatic.net/972590...,"Lagos, Mushin",Used,60000.0
7,Steering Horn Control for Corolla 2005,"₦ 10,000",If your horn don’t blow again contact me on090...,https://pictures-nigeria.jijistatic.net/983614...,"Lagos, Mushin",Used,12000.0
8,Shock Absorber Pad for All Motor,"₦ 30,000",Original shock absorber pad made from good Tha...,https://pictures-nigeria.jijistatic.net/304998...,Lagos,Brand New,36000.0
9,Original Bushing For All Cars,"₦ 4,000",Original bushing for your lower arm and your s...,https://pictures-nigeria.jijistatic.net/358214...,Lagos,Brand New,4800.0
10,Dm for Front Windscreen Is 250 2010 Available Now,"₦ 80,000",Welcome to U.C global enterprises.Auto part n ...,https://pictures-nigeria.jijistatic.net/157866...,"Lagos, Mushin",Brand New,96000.0
11,Abro Silicon 2000 Clear- White Black,"₦ 4,000",Abro 2000 clear silicone black and white,https://pictures-nigeria.jijistatic.net/129678...,"Lagos, Ojo",Bulk prices,4800.0
12,Honda Spare Parts,"₦ 7,500",We deal on honda spare parts such as direct to...,https://pictures-nigeria.jijistatic.net/519350...,"Abuja, Apo District",Used,9000.0
13,"Honda Driving Shaft, Shucks, Hub Bearing Steer...","₦ 15,000",We sale all types of Honda spare parts Such as...,https://pictures-nigeria.jijistatic.net/109511...,"Abuja, Apo District",Used,18000.0
14,2gr Engine for Toyota Camry 2012 V6,"₦ 1,200,000",Direct tokumbo with 2months guarantee,https://pictures-nigeria.jijistatic.net/171981...,"Lagos, Mushin",Used,1440000.0
15,Universal Android Screen,"₦ 85,000",Android screen plug and play with Bluetooth re...,https://pictures-nigeria.jijistatic.net/132891...,"Lagos, Ojo",Brand New,102000.0
16,Hub Bearing for All Cars (Japan Standard),"₦ 35,000",Original complete hub bearing for all cars ava...,https://pictures-nigeria.jijistatic.net/416521...,Lagos,Brand New,42000.0
17,Gx470 Converted to Prado 2020 Model,"₦ 1,600,000",Rim. Tyar. Front and back light,https://pictures-nigeria.jijistatic.net/168986...,"Lagos, Mushin",Brand New,1920000.0
18,Upgrade Kit for Mercedes Gl450 2008 to 2018 Av...,"₦ 8,000,000",Welcome to U.C global enterprises.Auto part n ...,https://pictures-nigeria.jijistatic.net/162011...,"Lagos, Mushin",Brand New,9600000.0
19,Upgrade Your Mercedes G Wagon 2025 Model,"₦ 28,000,000",Upgrade your Mercedes Benz G wagon 2025 model ...,https://pictures-nigeria.jijistatic.net/170650...,"Lagos, Mushin",Brand New,33600000.0
20,New Tires With Good Qualities,"₦ 65,000","I Sale All types of motor Tires, New one or Be...",https://pictures-nigeria.jijistatic.net/135497...,"Abuja, Apo District",Brand New,78000.0
21,Auto Base 1kg Pure White Paint,"₦ 12,500",Auto base 1kg pure white paint,https://pictures-nigeria.jijistatic.net/158433...,"Lagos, Ojo",Brand New,15000.0
22,Gearbox Toyota Camry 2004 Model Direct Tokunbo,"₦ 600,000",Gearbox Toyota camry 2004 model is available a...,https://pictures-nigeria.jijistatic.net/174067...,"Lagos, Mushin",Used,720000.0
23,All Kind of Mercedes-Benz Headlight Light,"₦ 20,000",Available now for sale,https://pictures-nigeria.jijistatic.net/151128...,"Lagos, Mushin",Brand New,24000.0

In [12]:
# df.to_excel('jiji_full_data.xlsx', index = False)

# Scraping BBC site

In [25]:
url = 'https://www.bbc.com/'
service = Service(executable_path = "C:/Users/HP/Downloads/chromedriver-win64/chromedriver-win64/chromedriver.exe")
driver = webdriver.Chrome(service = service)
driver.get(url)

In [32]:
# getting one news title
news_caption = driver.find_element(By.CLASS_NAME, 'sc-9d830f2a-3')


news = driver.find_element(By.CLASS_NAME, 'sc-36e63c4d-0')

news_region = driver.find_element(By.CLASS_NAME, 'sc-1907e52a-2')
driver.find_element(By.TAG_NAME, 'img').get_attribute('src')

'https://ichef.bbci.co.uk/news/480/cpsprodpb/09ab/live/bfb0c270-6983-11f0-89ea-4d6f9851f623.jpg.webp'