In [1]:
# # First check the things that are allowed on the website by first browsing the site with .robots.txt (eg, google.robots.txt)

# !pip install requests beautifulsoup4 lxml scrapy

In [2]:
# Fetching web pages with requests
import requests

url = "https://www.example.com"
response = requests.get(url)
if response.status_code == 200:
    print("Successful")
else:
    print("Not Successful")

Successful

In [3]:
# Handling response content
html_content = response.text
print (html_content)

<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
        background-color: #f0f0f2;
        margin: 0;
        padding: 0;
        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;

    }
    div {
        width: 600px;
        margin: 5em auto;
        padding: 2em;
        background-color: #fdfdff;
        border-radius: 0.5em;
        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);
    }
    a:link, a:visited {
        color: #38488f;
        text-decoration: none;
    }
    @media (max-width: 700px) {
        div {
            margin: 0 auto;
            width: auto;
        }
    }
    </style>
</head>

<body>
<div>
    <h1>Example Domain</h1>
    <p>This domain is for use in illustrative examples in documents. You may use this
    domain in literature without prior coordination or asking for permission.</p>
    <p><a href="https://www.iana.org/domains/example">More information...</a></p>
</div>
</body>
</html>

In [4]:
# Parsing our content
from bs4 import BeautifulSoup as bs

content_text = bs(html_content, 'lxml')
content_text.prettify()

'<!DOCTYPE html>\n<html>\n <head>\n  <title>\n   Example Domain\n  </title>\n  <meta charset="utf-8"/>\n  <meta content="text/html; charset=utf-8" http-equiv="Content-type"/>\n  <meta content="width=device-width, initial-scale=1" name="viewport"/>\n  <style type="text/css">\n   body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 2em;\n        background-color: #fdfdff;\n        border-radius: 0.5em;\n        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        div {\n            margin: 0 auto;\n            width: auto;\n        }\n    }\n  </style>\n </head>\n <body>\n  <div>\n   <h1>\n    Example Domain\n   </h1>\n   <p>\n    This domain is for use in illustrative examples in documents. You may use this\n    domain in literature without prior coordination or asking for permission.\n   </p>\n   <p>\n    <a href="https://www.iana.org/domains/example">\n     More information...\n    </a>\n   </p>\n  </div>\n </body>\n</html>\n'

In [5]:
# Navigating the D.O.M
head = content_text.find('h1')
head.text #this removes the parent tag

'Example Domain'

In [6]:
paragraph = content_text.find('p')
paragraph.text

'This domain is for use in illustrative examples in documents. You may use this\n    domain in literature without prior coordination or asking for permission.'

In [7]:
anchor = content_text.find('a')
anchor

In [8]:
response = requests.get('https://www.efcc.gov.ng/efcc/')
html_content = response.text
soup = bs(html_content, 'lxml')
print(soup.prettify())

<!DOCTYPE html>
<html class="j4" dir="ltr" lang="en-gb" xml:lang="en-gb" xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <link href="https://fonts.googleapis.com/css2?family=Barlow&amp;family=Roboto+Condensed&amp;family=Teko:wght@700&amp;family=DM+Sans&amp;display=swap" rel="stylesheet"/>
  <meta charset="utf-8"/>
  <meta content="Econimic and Financial Crimes Commission - DEMO Site" name="description"/>
  <meta content="Joomla! - Open Source Content Management" name="generator"/>
  <title>
   Economic and Financial Crimes Commission - EFCC - Economic and Financial Crimes Commission
  </title>
  <link href="/efcc/images/joomlart/logo/logo.png" rel="shortcut icon" type="image/vnd.microsoft.icon"/>
  <link href="https://www.efcc.gov.ng/efcc/other-pages/smart-search?format=opensearch" rel="search" title="OpenSearch Economic and Financial Crimes Commission - EFCC" type="application/opensearchdescription+xml"/>
  <link href="/efcc/plugins/system/t4/themes/base/vendors/font-awesome5/css/all.min.css?0e264d41c42d155571267399ab6c1b94" rel="stylesheet"/>
  <link href="/efcc/plugins/system/t4/themes/base/vendors/font-awesome/css/font-awesome.min.css?0e264d41c42d155571267399ab6c1b94" rel="stylesheet"/>
  <link href="/efcc/plugins/system/t4/themes/base/vendors/icomoon/css/icomoon.css?0e264d41c42d155571267399ab6c1b94" rel="stylesheet"/>
  <link href="/efcc/templates/ja_justitia/js/owl-carousel/owl.carousel.min.css?0e264d41c42d155571267399ab6c1b94" rel="stylesheet"/>
  <link href="/efcc/templates/ja_justitia/fonts/ionicons/css/ionicons.min.css?0e264d41c42d155571267399ab6c1b94" rel="stylesheet"/>
  <link href="/efcc/media/vendor/awesomplete/css/awesomplete.css?1.1.5" rel="stylesheet"/>
  <link href="/efcc/media/t4/optimize/css/d08afae994cf552882f88c641dc39bb5.css?b1a9ee8062f73048ca2ea757d3db5ae3" rel="stylesheet"/>
  <link href="/efcc/templates/ja_justitia/css/template.css?05b43cae25770cde57266b011df5d694" rel="stylesheet"/>
  <link href="/efcc/media/t4/optimize/css/9358fd99cd024f1a450a7a95347f9752.css?ab6d30d576be0a32ba88cf6a58866dce" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Didact+Gothic%7CPrata" rel="stylesheet"/>
  <script class="joomla-script-options new" type="application/json">
   {"joomla.jtext":{"RLTA_BUTTON_SCROLL_LEFT":"Scroll buttons to the left","RLTA_BUTTON_SCROLL_RIGHT":"Scroll buttons to the right","MOD_FINDER_SEARCH_VALUE":"Search &hellip;","JLIB_JS_AJAX_ERROR_OTHER":"An error has occurred while fetching the JSON data: HTTP %s status code.","JLIB_JS_AJAX_ERROR_PARSE":"A parse error has occurred while processing the following JSON data:<br><code style=\"color:inherit;white-space:pre-wrap;padding:0;margin:0;border:0;background:inherit;\">%s<\/code>"},"media-picker-api":{"apiBaseUrl":"https:\/\/www.efcc.gov.ng\/efcc\/index.php?option=com_media&format=json"},"finder-search":{"url":"\/efcc\/component\/finder\/?task=suggestions.suggest&format=json&tmpl=component&Itemid=101"},"system.paths":{"root":"\/efcc","rootFull":"https:\/\/www.efcc.gov.ng\/efcc\/","base":"\/efcc","baseFull":"https:\/\/www.efcc.gov.ng\/efcc\/"},"csrf.token":"aa31d751d749efecb495bd5bd198a88e"}
  </script>
  <script src="/efcc/media/system/js/core.min.js?37ffe4186289eba9c5df81bea44080aff77b9684">
  </script>
  <script defer="" nomodule="" src="/efcc/media/com_finder/js/finder-es5.min.js?e6d3d1f535e33b5641e406eb08d15093e7038cc2">
  </script>
  <script defer="" nomodule="" src="/efcc/media/vendor/bootstrap/js/bootstrap-es5.min.js?5.3.2">
  </script>
  <script src="/efcc/media/vendor/jquery/js/jquery.min.js?3.7.1">
  </script>
  <script src="/efcc/media/legacy/js/jquery-noconflict.min.js?647005fc12b79b3ca2bb30c059899d5994e3e34d">
  </script>
  <script src="/efcc/media/vendor/jquery-migrate/js/jquery-migrate.min.js?3.4.1">
  </script>
  <script src="/efcc/plugins/system/t4/themes/base/vendors/bootstrap/js/bootstrap.bundle.min.js?0e264d41c42d155571267399ab6c1b94">
  </script>
  <script src="/efcc/templates/ja_justitia/js/owl-carousel/owl.carousel.min.js?0e264d41c42d155571267399ab6c1b94">
  </script>
  <script defer="" src="/efcc/media/vendor/awesomplete/js/awesomplete.min.js?1.1.5">
  </script>
  <script src="/efcc/media/com_finder/js/finder.min.js?a2c3894d062787a266d59d457ffba5481b639f64" type="module">
  </script>
  <script src="/efcc/media/vendor/bootstrap/js/dropdown.min.js?5.3.2" type="module">
  </script>
  <script src="/efcc/media/vendor/bootstrap/js/collapse.min.js?5.3.2" type="module">
  </script>
  <script src="/efcc/media/t4/optimize/js/3252e5b199b9ec8ed4b04eb552b7e338.js?b1a9ee8062f73048ca2ea757d3db5ae3">
  </script>
  <script>
   rltaSettings = {"switchToAccordions":true,"switchBreakPoint":576,"buttonScrollSpeed":5,"addHashToUrls":true,"rememberActive":false,"wrapButtons":false}
  </script>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=yes" name="viewport"/>
  <style type="text/css">
   @-webkit-viewport   { width: device-width; }
    @-moz-viewport      { width: device-width; }
    @-ms-viewport       { width: device-width; }
    @-o-viewport        { width: device-width; }
    @viewport           { width: device-width; }
  </style>
  <meta content="true" name="HandheldFriendly"/>
  <meta content="YES" name="apple-mobile-web-app-capable"/>
  <!-- //META FOR IOS & HANDHELD -->
 </head>
 <body class="site-default navigation-default theme-default layout-home nav-breakpoint-lg navigation-hide oc-desktop com_content view-article item-101" data-jver="4">
  <div class="t4-offcanvas" data-offcanvas-options='{"modifiers":"right,overlay"}' id="off-canvas-right" role="complementary" style="display:none;">
   <div class="t4-off-canvas-header">
    <a href="https://www.efcc.gov.ng/efcc/" title="Economic and Financial Crimes Commission - EFCC">
     <img alt="Economic and Financial Crimes Commission - EFCC" class="logo-img-sm d-block d-sm-none" src="/efcc/images/joomlart/logo/logo-mobile.png"/>
     <img alt="Economic and Financial Crimes Commission - EFCC" class="logo-img d-none d-sm-block" src="/efcc/images/joomlart/logo/logo.png"/>
    </a>
    <button aria-hidden="true" class="close js-offcanvas-close" data-dismiss="modal" type="button">
     ×
    </button>
   </div>
   <div class="t4-off-canvas-body menu-item-def" data-effect="def">
    <div class="t4-module module" id="Mod120">
     <div class="module-inner">
      <div class="module-ct">
       <nav class="navbar">
        <ul class="nav navbar-nav">
         <li class="nav-item item-330">
          <a class="nav-link" href="https://www.efcc.gov.ng/efcc/index.php" itemprop="url">
           <span itemprop="name">
            <span class="menu-item-title">
             Home
            </span>
           </span>
          </a>
         </li>
         <li class="nav-item item-379 deeper dropdown parent" data-level="1">
          <a aria-expanded="false" aria-haspopup="true" class="nav-header nav-link dropdown-toggle" data-toggle="dropdown" href="javascript:;" itemprop="url" role="button">
           <span itemprop="name">
            <span class="menu-item-title">
             About Us
            </span>
           </span>
          </a>
          <ul class="dropdown-menu" data-bs-popper="static">
           <li class="nav-item item-380">
            <a class="dropdown-item" href="/efcc/about-us-new/leadership" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               LEADERSHIP
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-381">
            <a class="dropdown-item" href="/efcc/about-us-new/vision-mission" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               VISION &amp; MISSION
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-382">
            <a class="dropdown-item" href="/efcc/about-us-new-4/history-of-efcc" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               HISTORY OF EFCC
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-383">
            <a class="dropdown-item" href="/efcc/about-us-new-4/board-members" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               BOARD MEMBERS
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-384">
            <a class="dropdown-item" href="/efcc/about-us-new-4/the-establishment-act" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               THE ESTABLISHMENT ACT
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-385">
            <a class="dropdown-item" href="/efcc/about-us-new-4/efcc-strategic-plan" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               EFCC STRATEGIC PLAN
              </span>
             </span>
            </a>
           </li>
          </ul>
         </li>
         <li class="nav-item item-342 deeper dropdown parent" data-level="1">
          <a aria-expanded="false" aria-haspopup="true" class="nav-header nav-link dropdown-toggle" data-toggle="dropdown" href="javascript:;" itemprop="url" role="button">
           <span itemprop="name">
            <span class="menu-item-title">
             News &amp; Information
            </span>
           </span>
          </a>
          <ul class="dropdown-menu" data-bs-popper="static">
           <li class="nav-item item-343">
            <a class="dropdown-item" href="/efcc/news-and-information/news-release" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               NEWS
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-344">
            <a class="dropdown-item" href="/efcc/news-and-information/trending-news" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               TRENDING NEWS
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-345">
            <a class="dropdown-item" href="/efcc/news-and-information/wanted-persons-1" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               WANTED PERSONS
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-350">
            <a class="dropdown-item" href="/efcc/news-and-information/cartoon-zone" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               CARTOON ZONE
              </span>
             </span>
            </a>
           </li>
          </ul>
         </li>
         <li class="nav-item item-391">
          <a class="nav-link" href="/efcc/public-notices-4" itemprop="url">
           <span itemprop="name">
            <span class="menu-item-title">
             Convictions
            </span>
           </span>
          </a>
         </li>
         <li class="nav-item item-360">
          <a class="nav-link" href="/efcc/channels-of-reporting-complaints-2" itemprop="url">
           <span itemprop="name">
            <span class="menu-item-title">
             Channels of Reporting Complaints
            </span>
           </span>
          </a>
         </li>
         <li class="nav-item item-367 deeper dropdown parent" data-level="1">
          <a aria-expanded="false" aria-haspopup="true" class="nav-header nav-link dropdown-toggle" data-toggle="dropdown" href="javascript:;" itemprop="url" role="button">
           <span itemprop="name">
            <span class="menu-item-title">
             Resources
            </span>
           </span>
          </a>
          <ul class="dropdown-menu" data-bs-popper="static">
           <li class="nav-item item-434">
            <a class="dropdown-item" href="/efcc/records-3/interim-forfeiture" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               INTERIM FORFEITURE
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-371">
            <a class="dropdown-item" href="/efcc/records-3/efcc-operational-statistics" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               EFCC OPERATIONAL STATISTICS
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-372">
            <a class="dropdown-item" href="/efcc/records-3/archives" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               ARCHIVES
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-373 deeper dropdown dropright dropend parent" data-level="2">
            <a aria-expanded="false" aria-haspopup="true" class="nav-header dropdown-item dropdown-toggle" data-toggle="dropdown" href="javascript:;" itemprop="url" role="button">
             <span itemprop="name">
              <span class="menu-item-title">
               RED ALERT
              </span>
             </span>
            </a>
            <ul class="dropdown-menu" data-bs-popper="static">
             <li class="nav-item item-415">
              <a class="dropdown-item" href="/efcc/records-3/red-alert/red-alert-on-scam" itemprop="url">
               <span itemprop="name">
                <span class="menu-item-title">
                 RED ALERT ON SCAM
                </span>
               </span>
              </a>
             </li>
             <li class="nav-item item-414">
              <a class="dropdown-item" href="/efcc/records-3/red-alert/what-we-investigate" itemprop="url">
               <span itemprop="name">
                <span class="menu-item-title">
                 WHAT WE INVESTIGATE
                </span>
               </span>
              </a>
             </li>
            </ul>
           </li>
           <li class="nav-item item-374">
            <a class="dropdown-item" href="/efcc/records-3/scam-safety" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               SCAM &amp; SAFETY
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-376">
            <a class="dropdown-item" href="/efcc/records-3/efcc-alert" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               EFCC ALERT
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-377">
            <a class="dropdown-item" href="/efcc/records-3/efcc-strategic-plan" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               EFCC STRATEGIC PLAN
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-410">
            <a class="dropdown-item" href="/efcc/records-3/speeches" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               SPEECHES
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-411">
            <a class="dropdown-item" href="/efcc/records-3/zero-tolerance" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               ZERO TOLERANCE
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-412">
            <a class="dropdown-item" href="/efcc/records-3/advert" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               ADVERT
              </span>
             </span>
            </a>
           </li>
           <li class="nav-item item-417">
            <a class="dropdown-item" href="/efcc/records-3/eagle-eye-app" itemprop="url">
             <span itemprop="name">
              <span class="menu-item-title">
               EAGLE EYE APP
              </span>
             </span>
            </a>
           </li>
          </ul>
         </li>
         <li class="nav-item item-366">
          <a class="nav-link" href="/efcc/zonal-offices-2" itemprop="url">
           <span itemprop="name">
            <span class="menu-item-title">
             Zonal Commands
            </span>
           </span>
          </a>
         </li>
         <li class="nav-item item-378">
          <a class="nav-link" href="/efcc/get-in-touch-2" itemprop="url">
           <span itemprop="name">
            <span class="menu-item-title">
             Contact Us
            </span>
           </span>
          </a>
         </li>
         <li class="nav-item item-392">
          <a class="nav-link" href="/efcc/glossary" itemprop="url">
           <span itemprop="name">
            <span class="menu-item-title">
             GLOSSARY
            </span>
           </span>
          </a>
         </li>
         <li class="nav-item item-393">
          <a class="nav-link" href="/efcc/faq-standalone" itemprop="url">
           <span itemprop="name">
            <span class="menu-item-title">
             FAQ
            </span>
           </span>
          </a>
         </li>
         <li class="nav-item item-395">
          <a class="nav-link" href="/efcc/careers" itemprop="url">
           <span itemprop="name">
            <span class="menu-item-title">
             CAREERS
            </span>
           </span>
          </a>
         </li>
         <li class="nav-item item-394">
          <a class="nav-link" href="/efcc/auction" itemprop="url">
           <span itemprop="name">
            <span class="menu-item-title">
             Auction
            </span>
           </span>
          </a>
         </li>
         <li class="nav-item item-678">
          <a class="nav-link" href="/efcc/public-complaints-desk" itemprop="url">
           <span itemprop="name">
            <span class="menu-item-title">
             PUBLIC COMPLAINTS DESK
            </span>
           </span>
          </a>
         </li>
        </ul>
       </nav>
      </div>
     </div>
    </div>
   </div>
  </div>
  <main>
   <div class="t4-wrapper">
    <div class="t4-content">
     <div class="t4-content-inner">
      <div class="t4-section t4-header t4-sticky" id="t4-header">
       <!-- HEADER BLOCK -->
       <header class="t4-header" id="t4-header-wrap">
        <div class="t4-topbar">
         <div class="container">
          <div class="row no-gutters">
           <div class="t4-topbar-left d-none d-lg-block col-lg-8">
            <div class="custom">
             <!--ul class="contact-list">
<li><a href="#" title="Address">No. 5, Fomella Street, Off Adetokunbo Ademola Crescent, Wuse II, Abuja, Nigeria.</a></li>
<li><a href="#" title="Hotline">+234 99 044 0000 <br />+234 809 332 2644 </a>&nbsp; &nbsp;</li>
</ul-->
            </div>
           </div>
           <div class="t4-topbar-right col-12 col-lg-4 d-flex justify-content-end">
            <div class="custom">
             <ul class="social-list">
              <li>
               <a href="https://www.facebook.com/officialefcc/" rel="noopener" target="_blank" title="facebook">
                <span aria-hidden="true" class="fab fa-facebook-f">
                </span>
                <span class="d-none">
                 facebook
                </span>
               </a>
              </li>
              <li>

In [9]:
soup.find('strong').text

'VISION'

In [10]:
paragraph = soup.find_all('p')
count  = 1
for para in paragraph:
    print(f"Paragraph {count}: {para.text}")
    count += 1

Paragraph 1: Accessing the EFCC Eagle Eye App
Paragraph 2: EFCC Corporate Head Quarters,  Jabi- Abuja.
Paragraph 3: EFCC 10 – storey building, Jabi - Abuja.
Paragraph 4: Cadet Officers of the EFCC on parade during the passing out Parade (POP) of D1 Course 5 at the Nigerian Defence Academy (NDA), Kaduna.
Paragraph 5: EFCC Corporate Head Quarters,  Jabi - Abuja - 1
Paragraph 6: VISIONA Nigeria free of economic and financial crimes.
Paragraph 7: MISSION To eradicate economic and financial crimes through prevention, enforcement and coordination.
Paragraph 8: CORE VALUESThe core values of the EFCC are Integrity, Professionalism, Courage, and Collaboration.
Paragraph 9: CORPORATE HEADQUARTERS Plot 301/302, Institution and Research Cadastral District, Jabi, Abuja, Nigeria.
Paragraph 10: Hotline / Central Email+234 8093322644     +234 (9) 9044751
Paragraph 11:
Paragraph 12: Listen Now:

In [11]:
response = requests.get('https://www.efcc.gov.ng/efcc/news-and-information/wanted-persons-1')
html_content = response.text

soup = bs(html_content, 'lxml')
soup

<!DOCTYPE html>
<html class="j4" dir="ltr" lang="en-gb" xml:lang="en-gb" xmlns="http://www.w3.org/1999/xhtml">
<head>
<link href="https://fonts.googleapis.com/css2?family=Barlow&amp;family=Roboto+Condensed&amp;family=Teko:wght@700&amp;family=DM+Sans&amp;display=swap" rel="stylesheet"/>
<meta charset="utf-8"/>
<meta content="Econimic and Financial Crimes Commission" name="description"/>
<meta content="Joomla! - Open Source Content Management" name="generator"/>
<title>Economic and Financial Crimes Commission - EFCC - WANTED PERSONS</title>
<link href="/efcc/news-and-information/wanted-persons-1?format=feed&amp;type=rss" rel="alternate" title="Economic and Financial Crimes Commission - EFCC - WANTED PERSONS" type="application/rss+xml"/>
<link href="/efcc/news-and-information/wanted-persons-1?format=feed&amp;type=atom" rel="alternate" title="Economic and Financial Crimes Commission - EFCC - WANTED PERSONS" type="application/atom+xml"/>
<link href="/efcc/images/joomlart/logo/logo.png" rel="shortcut icon" type="image/vnd.microsoft.icon"/>
<link href="https://www.efcc.gov.ng/efcc/other-pages/smart-search?format=opensearch" rel="search" title="OpenSearch Economic and Financial Crimes Commission - EFCC" type="application/opensearchdescription+xml"/>
<link href="/efcc/plugins/system/t4/themes/base/vendors/font-awesome5/css/all.min.css?0e264d41c42d155571267399ab6c1b94" rel="stylesheet"/>
<link href="/efcc/plugins/system/t4/themes/base/vendors/font-awesome/css/font-awesome.min.css?0e264d41c42d155571267399ab6c1b94" rel="stylesheet"/>
<link href="/efcc/plugins/system/t4/themes/base/vendors/icomoon/css/icomoon.css?0e264d41c42d155571267399ab6c1b94" rel="stylesheet"/>
<link href="/efcc/templates/ja_justitia/js/owl-carousel/owl.carousel.min.css?0e264d41c42d155571267399ab6c1b94" rel="stylesheet"/>
<link href="/efcc/templates/ja_justitia/fonts/ionicons/css/ionicons.min.css?0e264d41c42d155571267399ab6c1b94" rel="stylesheet"/>
<link href="/efcc/media/vendor/awesomplete/css/awesomplete.css?1.1.5" rel="stylesheet"/>
<link href="/efcc/media/vendor/joomla-custom-elements/css/joomla-alert.min.css?0.2.0" rel="stylesheet"/>
<link href="/efcc/media/t4/optimize/css/6e0fee8a847e01739ac8a0f58375317c.css?b1a9ee8062f73048ca2ea757d3db5ae3" rel="stylesheet"/>
<link href="/efcc/templates/ja_justitia/css/template.css?05b43cae25770cde57266b011df5d694" rel="stylesheet"/>
<link href="/efcc/media/t4/optimize/css/6e4be481bf67ce3df5c193ac1c260026.css?d0e95e5142b59fb8702ffee85336b3fc" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Didact+Gothic%7CPrata" rel="stylesheet"/>
<script src="/efcc/media/vendor/jquery/js/jquery.min.js?3.7.1"></script>
<script class="joomla-script-options new" type="application/json">{"joomla.jtext":{"RLTA_BUTTON_SCROLL_LEFT":"Scroll buttons to the left","RLTA_BUTTON_SCROLL_RIGHT":"Scroll buttons to the right","MOD_FINDER_SEARCH_VALUE":"Search &hellip;","JLIB_JS_AJAX_ERROR_OTHER":"An error has occurred while fetching the JSON data: HTTP %s status code.","JLIB_JS_AJAX_ERROR_PARSE":"A parse error has occurred while processing the following JSON data:<br><code style=\"color:inherit;white-space:pre-wrap;padding:0;margin:0;border:0;background:inherit;\">%s<\/code>","ERROR":"Error","MESSAGE":"Message","NOTICE":"Notice","WARNING":"Warning","JCLOSE":"Close","JOK":"OK","JOPEN":"Open"},"finder-search":{"url":"\/efcc\/component\/finder\/?task=suggestions.suggest&format=json&tmpl=component&Itemid=101"},"system.paths":{"root":"\/efcc","rootFull":"https:\/\/www.efcc.gov.ng\/efcc\/","base":"\/efcc","baseFull":"https:\/\/www.efcc.gov.ng\/efcc\/"},"csrf.token":"fedc11dc3e2d7d943eb81eff08a026e8"}</script>
<script src="/efcc/media/system/js/core.min.js?37ffe4186289eba9c5df81bea44080aff77b9684"></script>
<script defer="" nomodule="" src="/efcc/media/vendor/webcomponentsjs/js/webcomponents-bundle.min.js?2.8.0"></script>
<script defer="" nomodule="" src="/efcc/media/com_finder/js/finder-es5.min.js?e6d3d1f535e33b5641e406eb08d15093e7038cc2"></script>
<script defer="" nomodule="" src="/efcc/media/system/js/messages-es5.min.js?c29829fd2432533d05b15b771f86c6637708bd9d"></script>
<script defer="" nomodule="" src="/efcc/media/vendor/bootstrap/js/bootstrap-es5.min.js?5.3.2"></script>
<script defer="" nomodule="" src="/efcc/media/system/js/joomla-hidden-mail-es5.min.js?b2c8377606bb898b64d21e2d06c6bb925371b9c3"></script>
<script src="/efcc/media/system/js/joomla-hidden-mail.min.js?065992337609bf436e2fedbcbdc3de1406158b97" type="module"></script>
<script src="/efcc/media/legacy/js/jquery-noconflict.min.js?647005fc12b79b3ca2bb30c059899d5994e3e34d"></script>
<script src="/efcc/media/vendor/jquery-migrate/js/jquery-migrate.min.js?3.4.1"></script>
<script src="/efcc/plugins/system/t4/themes/base/vendors/bootstrap/js/bootstrap.bundle.min.js?0e264d41c42d155571267399ab6c1b94"></script>
<script src="/efcc/templates/ja_justitia/js/owl-carousel/owl.carousel.min.js?0e264d41c42d155571267399ab6c1b94"></script>
<script defer="" src="/efcc/media/vendor/awesomplete/js/awesomplete.min.js?1.1.5"></script>
<script src="/efcc/media/com_finder/js/finder.min.js?a2c3894d062787a266d59d457ffba5481b639f64" type="module"></script>
<script src="/efcc/media/system/js/messages.min.js?7f7aa28ac8e8d42145850e8b45b3bc82ff9a6411" type="module"></script>
<script src="/efcc/media/vendor/bootstrap/js/dropdown.min.js?5.3.2" type="module"></script>
<script src="/efcc/media/vendor/bootstrap/js/collapse.min.js?5.3.2" type="module"></script>
<script src="/efcc/media/t4/optimize/js/bab30cf601bdc02310487b16a34ceb96.js?b1a9ee8062f73048ca2ea757d3db5ae3"></script>
<script>rltaSettings = {"switchToAccordions":true,"switchBreakPoint":576,"buttonScrollSpeed":5,"addHashToUrls":true,"rememberActive":false,"wrapButtons":false}</script>
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=yes" name="viewport"/>
<style type="text/css">
    @-webkit-viewport   { width: device-width; }
    @-moz-viewport      { width: device-width; }
    @-ms-viewport       { width: device-width; }
    @-o-viewport        { width: device-width; }
    @viewport           { width: device-width; }
  </style>
<meta content="true" name="HandheldFriendly"/>
<meta content="YES" name="apple-mobile-web-app-capable"/>
<!-- //META FOR IOS & HANDHELD -->
</head>
<body class="site-default navigation-default theme-default layout-default nav-breakpoint-lg navigation-hide oc-desktop com_content view-category item-254" data-jver="4">
<div class="t4-offcanvas" data-offcanvas-options='{"modifiers":"right,overlay"}' id="off-canvas-right" role="complementary" style="display:none;">
<div class="t4-off-canvas-header">
<a href="https://www.efcc.gov.ng/efcc/" title="Economic and Financial Crimes Commission - EFCC">
<img alt="Economic and Financial Crimes Commission - EFCC" class="logo-img-sm d-block d-sm-none" src="/efcc/images/joomlart/logo/logo-mobile.png"/>
<img alt="Economic and Financial Crimes Commission - EFCC" class="logo-img d-none d-sm-block" src="/efcc/images/joomlart/logo/logo.png"/>
</a>
<button aria-hidden="true" class="close js-offcanvas-close" data-dismiss="modal" type="button">×</button>
</div>
<div class="t4-off-canvas-body menu-item-def" data-effect="def">
<div class="t4-module module" id="Mod120"><div class="module-inner"><div class="module-ct"><nav class="navbar">
<ul class="nav navbar-nav">
<li class="nav-item item-330"><a class="nav-link" href="https://www.efcc.gov.ng/efcc/index.php" itemprop="url"><span itemprop="name"><span class="menu-item-title">Home</span></span></a></li><li class="nav-item item-379 deeper dropdown parent" data-level="1"><a aria-expanded="false" aria-haspopup="true" class="nav-header nav-link dropdown-toggle" data-toggle="dropdown" href="javascript:;" itemprop="url" role="button">
<span itemprop="name"><span class="menu-item-title">About Us</span></span>
</a>
<ul class="dropdown-menu" data-bs-popper="static"><li class="nav-item item-380"><a class="dropdown-item" href="/efcc/about-us-new/leadership" itemprop="url"><span itemprop="name"><span class="menu-item-title">LEADERSHIP</span></span></a></li><li class="nav-item item-381"><a class="dropdown-item" href="/efcc/about-us-new/vision-mission" itemprop="url"><span itemprop="name"><span class="menu-item-title">VISION &amp; MISSION</span></span></a></li><li class="nav-item item-382"><a class="dropdown-item" href="/efcc/about-us-new-4/history-of-efcc" itemprop="url"><span itemprop="name"><span class="menu-item-title">HISTORY OF EFCC</span></span></a></li><li class="nav-item item-383"><a class="dropdown-item" href="/efcc/about-us-new-4/board-members" itemprop="url"><span itemprop="name"><span class="menu-item-title">BOARD MEMBERS</span></span></a></li><li class="nav-item item-384"><a class="dropdown-item" href="/efcc/about-us-new-4/the-establishment-act" itemprop="url"><span itemprop="name"><span class="menu-item-title">THE ESTABLISHMENT ACT</span></span></a></li><li class="nav-item item-385"><a class="dropdown-item" href="/efcc/about-us-new-4/efcc-strategic-plan" itemprop="url"><span itemprop="name"><span class="menu-item-title">EFCC STRATEGIC PLAN</span></span></a></li></ul></li><li class="nav-item item-342 deeper dropdown parent" data-level="1"><a aria-expanded="false" aria-haspopup="true" class="nav-header nav-link dropdown-toggle" data-toggle="dropdown" href="javascript:;" itemprop="url" role="button">
<span itemprop="name"><span class="menu-item-title">News &amp; Information</span></span>
</a>
<ul class="dropdown-menu" data-bs-popper="static"><li class="nav-item item-343"><a class="dropdown-item" href="/efcc/news-and-information/news-release" itemprop="url"><span itemprop="name"><span class="menu-item-title">NEWS</span></span></a></li><li class="nav-item item-344"><a class="dropdown-item" href="/efcc/news-and-information/trending-news" itemprop="url"><span itemprop="name"><span class="menu-item-title">TRENDING NEWS</span></span></a></li><li class="nav-item item-345 current active"><a class="dropdown-item" href="/efcc/news-and-information/wanted-persons-1" itemprop="url"><span itemprop="name"><span class="menu-item-title">WANTED PERSONS</span></span></a></li><li class="nav-item item-350"><a class="dropdown-item" href="/efcc/news-and-information/cartoon-zone" itemprop="url"><span itemprop="name"><span class="menu-item-title">CARTOON ZONE</span></span></a></li></ul></li><li class="nav-item item-391"><a class="nav-link" href="/efcc/public-notices-4" itemprop="url"><span itemprop="name"><span class="menu-item-title">Convictions </span></span></a></li><li class="nav-item item-360"><a class="nav-link" href="/efcc/channels-of-reporting-complaints-2" itemprop="url"><span itemprop="name"><span class="menu-item-title">Channels of Reporting Complaints</span></span></a></li><li class="nav-item item-367 deeper dropdown parent" data-level="1"><a aria-expanded="false" aria-haspopup="true" class="nav-header nav-link dropdown-toggle" data-toggle="dropdown" href="javascript:;" itemprop="url" role="button">
<span itemprop="name"><span class="menu-item-title">Resources</span></span>
</a>
<ul class="dropdown-menu" data-bs-popper="static"><li class="nav-item item-434"><a class="dropdown-item" href="/efcc/records-3/interim-forfeiture" itemprop="url"><span itemprop="name"><span class="menu-item-title">INTERIM FORFEITURE</span></span></a></li><li class="nav-item item-371"><a class="dropdown-item" href="/efcc/records-3/efcc-operational-statistics" itemprop="url"><span itemprop="name"><span class="menu-item-title">EFCC OPERATIONAL STATISTICS</span></span></a></li><li class="nav-item item-372"><a class="dropdown-item" href="/efcc/records-3/archives" itemprop="url"><span itemprop="name"><span class="menu-item-title">ARCHIVES</span></span></a></li><li class="nav-item item-373 deeper dropdown dropright dropend parent" data-level="2"><a aria-expanded="false" aria-haspopup="true" class="nav-header dropdown-item dropdown-toggle" data-toggle="dropdown" href="javascript:;" itemprop="url" role="button">
<span itemprop="name"><span class="menu-item-title">RED ALERT</span></span>
</a>
<ul class="dropdown-menu" data-bs-popper="static"><li class="nav-item item-415"><a class="dropdown-item" href="/efcc/records-3/red-alert/red-alert-on-scam" itemprop="url"><span itemprop="name"><span class="menu-item-title">RED ALERT ON SCAM</span></span></a></li><li class="nav-item item-414"><a class="dropdown-item" href="/efcc/records-3/red-alert/what-we-investigate" itemprop="url"><span itemprop="name"><span class="menu-item-title">WHAT WE INVESTIGATE</span></span></a></li></ul></li><li class="nav-item item-374"><a class="dropdown-item" href="/efcc/records-3/scam-safety" itemprop="url"><span itemprop="name"><span class="menu-item-title">SCAM &amp; SAFETY</span></span></a></li><li class="nav-item item-376"><a class="dropdown-item" href="/efcc/records-3/efcc-alert" itemprop="url"><span itemprop="name"><span class="menu-item-title">EFCC ALERT</span></span></a></li><li class="nav-item item-377"><a class="dropdown-item" href="/efcc/records-3/efcc-strategic-plan" itemprop="url"><span itemprop="name"><span class="menu-item-title">EFCC STRATEGIC PLAN</span></span></a></li><li class="nav-item item-410"><a class="dropdown-item" href="/efcc/records-3/speeches" itemprop="url"><span itemprop="name"><span class="menu-item-title">SPEECHES</span></span></a></li><li class="nav-item item-411"><a class="dropdown-item" href="/efcc/records-3/zero-tolerance" itemprop="url"><span itemprop="name"><span class="menu-item-title">ZERO TOLERANCE</span></span></a></li><li class="nav-item item-412"><a class="dropdown-item" href="/efcc/records-3/advert" itemprop="url"><span itemprop="name"><span class="menu-item-title">ADVERT</span></span></a></li><li class="nav-item item-417"><a class="dropdown-item" href="/efcc/records-3/eagle-eye-app" itemprop="url"><span itemprop="name"><span class="menu-item-title">EAGLE EYE APP</span></span></a></li></ul></li><li class="nav-item item-366"><a class="nav-link" href="/efcc/zonal-offices-2" itemprop="url"><span itemprop="name"><span class="menu-item-title">Zonal Commands</span></span></a></li><li class="nav-item item-378"><a class="nav-link" href="/efcc/get-in-touch-2" itemprop="url"><span itemprop="name"><span class="menu-item-title">Contact Us</span></span></a></li><li class="nav-item item-392"><a class="nav-link" href="/efcc/glossary" itemprop="url"><span itemprop="name"><span class="menu-item-title">GLOSSARY</span></span></a></li><li class="nav-item item-393"><a class="nav-link" href="/efcc/faq-standalone" itemprop="url"><span itemprop="name"><span class="menu-item-title">FAQ </span></span></a></li><li class="nav-item item-395"><a class="nav-link" href="/efcc/careers" itemprop="url"><span itemprop="name"><span class="menu-item-title">CAREERS</span></span></a></li><li class="nav-item item-394"><a class="nav-link" href="/efcc/auction" itemprop="url"><span itemprop="name"><span class="menu-item-title">Auction</span></span></a></li><li class="nav-item item-678"><a class="nav-link" href="/efcc/public-complaints-desk" itemprop="url"><span itemprop="name"><span class="menu-item-title">PUBLIC COMPLAINTS DESK</span></span></a></li></ul></nav></div></div></div>
</div>
</div>
<main>
<div class="t4-wrapper">
<div class="t4-content">
<div class="t4-content-inner">
<div class="t4-section t4-header t4-sticky" id="t4-header"><!-- HEADER BLOCK -->
<header class="t4-header" id="t4-header-wrap">
<div class="t4-topbar">
<div class="container">
<div class="row no-gutters">
<div class="t4-topbar-left d-none d-lg-block col-lg-8">
<div class="custom">
<!--ul class="contact-list">
<li><a href="#" title="Address">No. 5, Fomella Street, Off Adetokunbo Ademola Crescent, Wuse II, Abuja, Nigeria.</a></li>
<li><a href="#" title="Hotline">+234 99 044 0000 <br />+234 809 332 2644 </a>&nbsp; &nbsp;</li>
</ul--></div>
</div>
<div class="t4-topbar-right col-12 col-lg-4 d-flex justify-content-end">
<div class="custom">
<ul class="social-list">
<li><a href="https://www.facebook.com/officialefcc/" rel="noopener" target="_blank" title="facebook"><span aria-hidden="true" class="fab fa-facebook-f"></span><span class="d-none">facebook</span></a></li>
<li><a href="https://twitter.com/OfficialEFCC" rel="noopener" target="_blank" title="twitter"><span aria-hidden="true" class="fab fa-twitter"></span><span class="d-none">twitter</span></a></li>
<li><a href="https://www.instagram.com/officialefcc/" rel="noopener" target="_blank" title="instagram"><span aria-hidden="true" class="fab fa-instagram"></span><span class="d-none">instagram</span></a></li>
<li><a href="https://www.youtube.com/officialefcc" rel="noopener" target="_blank" title="YouTube"><span aria-hidden="true" class="fab fa-youtube"></span><span class="d-none">youtube</span></a></li>
</ul></div>
</div>
</div>
</div>
</div>
<div class="t4-header-inner">
<div class="container">
<div class="row no-gutters d-flex justify-content-between flex-nowrap">
<div class="col-auto t4-logo-header mr-auto mr-lg-0">
<div class="navbar-brand logo-image logo-control">
<a href="https://www.efcc.gov.ng/efcc/" title="Economic and Financial Crimes Commission - EFCC">
<img alt="Economic and Financial Crimes Commission - EFCC" class="logo-img-sm d-block d-sm-none" src="/efcc/images/joomlart/logo/logo-mobile.png"/>
<img alt="Economic and Financial Crimes Commission - EFCC" class="logo-img d-none d-sm-block" height="100" src="/efcc/images/joomlart/logo/logo.png" width="100"/>
</a>
</div>
</div>
<div class="col-auto t4-megamenu-wrap d-lg-block col-xl-8">
<div class="t4-navbar">
<nav class="navbar navbar-expand-lg">
<div class="t4-megamenu collapse navbar-collapse slide animate" data-duration="400" id="t4-megamenu-mainmenu">
<ul class="nav navbar-nav level0" itemscope="itemscope" itemtype="http://www.schema.org/SiteNavigationElement">
<li class="nav-item default" data-id="101" data-level="1"><a class="nav-link" href="/efcc/" itemprop="url"><span itemprop="name"><span class="menu-item-title">Home</span></span></a></li><li class="nav-item dropdown parent" data-id="179" data-level="1"><a aria-expanded="false" aria-haspopup="true" class="nav-header nav-link dropdown-toggle" href="javascript:;" itemprop="url" role="button">
<span itemprop="name"><span class="menu-item-title">About Us</span></span>
<i class="item-caret"></i></a>
<div class="dropdown-menu level1" data-bs-popper="static"><div class="dropdown-menu-inner"><ul><li class="nav-item" data-id="187" data-level="2"><a class="dropdown-item" href="/efcc/about-us-new/leadership" itemprop="url"><span itemprop="name"><span class="menu-item-title">LEADERSHIP</span></span></a></li><li class="nav-item" data-id="188" data-level="2"><a class="dropdown-item" href="/efcc/about-us-new/vision-mission" itemprop="url"><span itemprop="name"><span class="menu-item-title">VISION &amp; MISSION</span></span></a></li><li class="nav-item" data-id="190" data-level="2"><a class="dropdown-item" href="/efcc/about-us-new/history-of-efcc" itemprop="url"><span itemprop="name"><span class="menu-item-title">HISTORY OF EFCC</span></span></a></li><li class="nav-item" data-id="192" data-level="2"><a class="dropdown-item" href="/efcc/about-us-new/board-members" itemprop="url"><span itemprop="name"><span class="menu-item-title">BOARD MEMBERS</span></span></a></li><li class="nav-item" data-id="193" data-level="2"><a class="dropdown-item" href="/efcc/about-us-new/the-establishment-act" itemprop="url"><span itemprop="name"><span class="menu-item-title">THE ESTABLISHMENT ACT</span></span></a></li><li class="nav-item" data-id="236" data-level="2"><a class="dropdown-item" href="/efcc/about-us-new/efcc-strategic-plan" itemprop="url"><span itemprop="name"><span class="menu-item-title">EFCC STRATEGIC PLAN</span></span></a></li></ul></div></div></li><li class="nav-item active dropdown parent" data-id="180" data-level="1"><a aria-expanded="false" aria-haspopup="true" class="nav-header nav-link dropdown-toggle" href="javascript:;" itemprop="url" role="button">

In [12]:
images = soup.find_all('img')
for image in images:
    print(image)

<img alt="Economic and Financial Crimes Commission - EFCC" class="logo-img-sm d-block d-sm-none" src="/efcc/images/joomlart/logo/logo-mobile.png"/>
<img alt="Economic and Financial Crimes Commission - EFCC" class="logo-img d-none d-sm-block" src="/efcc/images/joomlart/logo/logo.png"/>
<img alt="Economic and Financial Crimes Commission - EFCC" class="logo-img-sm d-block d-sm-none" src="/efcc/images/joomlart/logo/logo-mobile.png"/>
<img alt="Economic and Financial Crimes Commission - EFCC" class="logo-img d-none d-sm-block" height="100" src="/efcc/images/joomlart/logo/logo.png" width="100"/>
<img height="2238" itemprop="thumbnail" loading="lazy" src="/efcc/images/news_info/news_release/July%202025/Wantewd%20by%20EFCC%20Akolawole.jpg" width="1615"/>
<img height="2238" itemprop="thumbnail" loading="lazy" src="/efcc/images/news_info/news_release/July%202025/Wantewd%20by%20EFCC%20Aminu%20Job.jpg" width="1616"/>
<img height="1123" itemprop="thumbnail" loading="lazy" src="/efcc/images/news_info/news_release/July%202025/SULE_JOSEPH_ENEJO_page-0001.jpg" width="812"/>
<img height="1080" itemprop="thumbnail" loading="lazy" src="/efcc/images/news_info/news_release/July%202025/WhatsApp%20Image%202025-07-11%20at%2015.45.09%202.jpg" width="779"/>
<img height="1350" itemprop="thumbnail" loading="lazy" src="/efcc/images/news_info/news_release/June%202025/WhatsApp%20Image%202025-06-13%20at%2016.51.50.jpg" width="1080"/>
<img height="750" itemprop="thumbnail" loading="lazy" src="/efcc/images/news_info/news_release/May_2025/ABIODUN_AND_FOLASHADE.jpg" width="1000"/>
<img alt="EFCC 97.3 fm" class="card-img-top" src="/efcc/images/radio/EFCC_97.3fm01.jpg"/>

### Scraping with class, ID, and attributes
class_ = "", <br>
id = "",<br>
.find('tag').get('attr')

In [13]:
wanted_persons = soup.find_all('figure', class_='pull-left item-image')
for person in wanted_persons:
    print(person.find('img').get('src'))

/efcc/images/news_info/news_release/July%202025/Wantewd%20by%20EFCC%20Akolawole.jpg
/efcc/images/news_info/news_release/July%202025/Wantewd%20by%20EFCC%20Aminu%20Job.jpg
/efcc/images/news_info/news_release/July%202025/SULE_JOSEPH_ENEJO_page-0001.jpg
/efcc/images/news_info/news_release/July%202025/WhatsApp%20Image%202025-07-11%20at%2015.45.09%202.jpg
/efcc/images/news_info/news_release/June%202025/WhatsApp%20Image%202025-06-13%20at%2016.51.50.jpg
/efcc/images/news_info/news_release/May_2025/ABIODUN_AND_FOLASHADE.jpg

In [14]:
wanted_persons = soup.find_all('figure', class_='pull-left item-image')
count  = 1
for person in wanted_persons:
    img_src = person.find('img').get('src')
    filename = img_src.split('/')
    print(f"File name {count}: {filename[-1]}")
    count += 1

File name 1: Wantewd%20by%20EFCC%20Akolawole.jpg
File name 2: Wantewd%20by%20EFCC%20Aminu%20Job.jpg
File name 3: SULE_JOSEPH_ENEJO_page-0001.jpg
File name 4: WhatsApp%20Image%202025-07-11%20at%2015.45.09%202.jpg
File name 5: WhatsApp%20Image%202025-06-13%20at%2016.51.50.jpg
File name 6: ABIODUN_AND_FOLASHADE.jpg

## Scraping JUMIA site

In [15]:
import pandas as pd

In [16]:
url = 'https://www.jumia.com.ng/'
response = requests.get(url)
html_content = response.text

soup = bs(html_content, 'lxml')

In [17]:
item = soup.find('div', class_ = 'itm col')
item_name = item.find('div', class_ = 'name').text
item_price = item.find('div', class_ = 'prc').text
item_discount = item.find('div', class_ = 'bdg _dsct').text
stock = item.find('div', class_ = 'stk').text

print(f"{item_name} is sold for {item_price} with a discount of {item_discount} and we have {stock}")

YARA Baby Diaper Size 2 Mini 3-6 Kg, Small Pack (10 Pcs) is sold for ₦ 730 with a discount of 16% and we have 19 items left

In [18]:
# Refreshing DataFrame memory on how to use it on Jumis site
dictionary = {
    'name': ['Ada', 'Tamuno', 'Joy','Brenda'],
    'Spouse': ['Emeka', 'Innocent', 'Great', 'Shola']
}

data = pd.DataFrame(dictionary)
data

     name    Spouse
0     Ada     Emeka
1  Tamuno  Innocent
2     Joy     Great
3  Brenda     Shola

In [24]:
url = 'https://www.jumia.com.ng/'
response = requests.get(url)
html_content = response.text
soup = bs(html_content, 'lxml')

data = []
page_items = soup.find_all('div', class_ = 'itm col')

for item in page_items:    
    item_name = item.find('div', class_ = 'name')
    name = item_name.text if item_name else 'NA' # returns 'NA' if it doesn't exist
    
    item_price = item.find('div', class_ = 'prc')
    price = item_price.text if item_price else 'NA'
    
    item_discount = item.find('div', class_ = 'bdg _dsct')
    discount = item_discount.text if item_discount else 'NA'
    
    item_stock = item.find('div', class_ = 'stk')
    stock = item_stock.text if item_stock else 'NA'

    goods = {
        'name': name,
        'price': price,
        'discount': discount,
        'stock': stock
    }

    data.append(goods)

data

[{'name': 'YARA Baby Diaper Size 2 Mini 3-6 Kg, Small Pack (10 Pcs)',
  'price': '₦ 730',
  'discount': '16%',
  'stock': '19 items left'},
 {'name': 'Ace Elec 50000 MAh Power Banks With LED Light Portable Super Fast Charger',
  'price': '₦ 24,882',
  'discount': '4%',
  'stock': '50 items left'},
 {'name': '6Inch LED Selfie Ring Light & Tripod Stand 2 Phone Holders',
  'price': '₦ 5,590',
  'discount': '53%',
  'stock': '77 items left'},
 {'name': 'NIVEA Dry Impact Roll-on For Men, 72h- 50ml (Pack Of 3)',
  'price': '₦ 5,085',
  'discount': '17%',
  'stock': '46 items left'},
 {'name': 'Roushun Vitamin C Serum [Anti-Aging Serum]---30ml',
  'price': '₦ 2,399',
  'discount': '52%',
  'stock': '50 items left'},
 {'name': 'Syinix 2.2L Electric Kettle - Silver SKE22U1',
  'price': '₦ 6,100',
  'discount': '4%',
  'stock': '50 items left'},
 {'name': 'NIVEA Perfect & Radiant Luminous630 Anti Dark Marks Serum - 30ml (Pack of 2)',
  'price': '₦ 16,450',
  'discount': '27%',
  'stock': '18 items left'},
 {'name': "XIAOMI Redmi 14C 6.88'' 4GB RAM/128GB ROM Android 14 -Midnight Black..",
  'price': '₦ 125,712',
  'discount': 'NA',
  'stock': '50 items left'},
 {'name': 'Infinix Hot 60i 6.78" 4GB RAM/128GB ROM Android 15- Silver',
  'price': '₦ 144,842',
  'discount': 'NA',
  'stock': '50 items left'},
 {'name': 'Aeon 85L Double Door Fridge (ART108GJ) - Dark Grey',
  'price': '₦ 183,700',
  'discount': '14%',
  'stock': '50 items left'},
 {'name': 'Hisense 7.5kg Twin Tub Washing Machine - (WSQB 753 (JF)',
  'price': '₦ 189,999',
  'discount': '19%',
  'stock': '50 items left'},
 {'name': 'Samsung Galaxy A05 6.7" 4GB RAM/64GB ROM Android 13 - Black',
  'price': '₦ 120,577',
  'discount': 'NA',
  'stock': '49 items left'},
 {'name': 'Haier Thermocool 200 Litres Chest Freezer (HTF-200) - Silver + 3 Years Warranty',
  'price': '₦ 392,915',
  'discount': '14%',
  'stock': '50 items left'},
 {'name': 'DELL Refurbishe Latitude E5470 14-Inch Laptop (Intel Core-i5-6300U Upto 3.0 GHz, 8GB RAM 256GB ROM',
  'price': '₦ 257,626',
  'discount': 'NA',
  'stock': '2 items left'},
 {'name': "TOUPHY Polo T-Shirts +Shorts Cotton Men's Short Sleeve Set",
  'price': '₦ 9,950 - ₦ 15,185',
  'discount': '50%',
  'stock': '80 items left'},
 {'name': 'itel TWS BudsFit 5 Earbuds C-Bridge Design  Starry Purple',
  'price': '₦ 22,798',
  'discount': '31%',
  'stock': 'NA'},
 {'name': 'Aeon 5Kg Twin Tub Washing Machine (ATT05J)',
  'price': '₦ 138,600',
  'discount': '17%',
  'stock': 'NA'},
 {'name': 'Century 43 Inches Smart 2K UHD TV (CTV-43) + 1 YEAR WARRANTY',
  'price': '₦ 199,999',
  'discount': '29%',
  'stock': 'NA'},
 {'name': 'NIVEA Sun UV Sunscreen Face Shine Control Cream SPF 50 - 50ml (Pack of 2)',
  'price': '₦ 17,065',
  'discount': '22%',
  'stock': 'NA'},
 {'name': 'ECOFLOW 980WH 500W E980 Portable Solar Generator For Home Backup',
  'price': '₦ 549,264',
  'discount': '62%',
  'stock': 'NA'},
 {'name': 'Syinix 2.2L Electric Kettle - Silver SKE22U1',
  'price': '₦ 6,100',
  'discount': '4%',
  'stock': 'NA'},
 {'name': 'HITHIUM HeroEE 1 1kWh Power Station With 1M Photovoltaic Conversion Cable+2 Year Warranty',
  'price': '₦ 290,010',
  'discount': '32%',
  'stock': 'NA'},
 {'name': 'Oraimo Traveler 4 20000mAh 10.5W Power Bank',
  'price': '₦ 13,488',
  'discount': '55%',
  'stock': 'NA'},
 {'name': 'Macbook PRO Laptop A1278 13.3 Inch Core I5 2.5GHz 8GB RAM 500GB EN/AR Keyboard',
  'price': '₦ 189,999',
  'discount': '1%',
  'stock': 'NA'},
 {'name': 'Aeon 4 Burner 50 x 50 Gas Cooker (AGC5040J) - Black',
  'price': '₦ 136,960',
  'discount': '14%',
  'stock': 'NA'},
 {'name': 'DIY Wall Clocks 3D Mirror Stickers Large Wall Clock -Black',
  'price': '₦ 3,574',
  'discount': '44%',
  'stock': 'NA'},
 {'name': 'Skechers  SKECH-AIR DYNAMIGHT - NEW GRIND - WOMEN',
  'price': '₦ 80,000',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'EASYPIE EasyPie 20000mAh Dual Fast Charge 64W Type-C And Micro-USB Portable Power Bank',
  'price': '₦ 7,392',
  'discount': '17%',
  'stock': 'NA'},
 {'name': 'Hc 16 inches Solar Rechargeable Standing Fan(C168) + Solar Panel-White',
  'price': '₦ 42,532',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'Philips Classic Dry Iron -Fast and Efficient Guaranteed-Fabrics best choice ',
  'price': '₦ 12,399',
  'discount': '66%',
  'stock': 'NA'},
 {'name': '', 'price': '', 'discount': 'NA', 'stock': 'NA'},
 {'name': '', 'price': '', 'discount': 'NA', 'stock': 'NA'},
 {'name': '', 'price': '', 'discount': 'NA', 'stock': 'NA'},
 {'name': '', 'price': '', 'discount': 'NA', 'stock': 'NA'},
 {'name': '', 'price': '', 'discount': 'NA', 'stock': 'NA'},
 {'name': '', 'price': '', 'discount': 'NA', 'stock': 'NA'},
 {'name': 'Hisense 20 Litres Microwave (H20MOWS14) - White With 1 Year Warranty',
  'price': '₦ 79,999',
  'discount': '1%',
  'stock': 'NA'},
 {'name': 'Nexus 18 Inch Standing Fan (NX-SF5400B)',
  'price': '₦ 27,500',
  'discount': '16%',
  'stock': 'NA'},
 {'name': 'Boscon Auto Ignition Table Top Gas Cooker-2 Burner-Silver',
  'price': '₦ 15,900',
  'discount': '10%',
  'stock': 'NA'},
 {'name': 'Syinix 2.2L Electric Kettle - Silver SKE22U1',
  'price': '₦ 6,100',
  'discount': '4%',
  'stock': 'NA'},
 {'name': 'Binatone Dry Iron (Di1255) + 2 Years Warranty',
  'price': '₦ 13,650',
  'discount': '17%',
  'stock': 'NA'},
 {'name': 'Nexus 1HP Split Air Conditioner (NX-MSSH9000SC) - White + Full Installation Kit & 2 Years Warranty',
  'price': '₦ 286,200',
  'discount': '17%',
  'stock': 'NA'},
 {'name': 'Skyrun 70 Litres Double Door Top Mount Fridge (BCD-85HC) - Starry Night Black.',
  'price': '₦ 188,490',
  'discount': '3%',
  'stock': 'NA'},
 {'name': 'Skyrun 100L Chest Freezer (BD-90A) - Grey',
  'price': '₦ 221,450',
  'discount': '3%',
  'stock': 'NA'},
 {'name': 'National Star Sandwich Maker + 12 Months Warranty:model number - NG-205',
  'price': '₦ 12,999',
  'discount': '7%',
  'stock': 'NA'},
 {'name': 'Glamstar 1.5HP Split Copper Air Conditioner (GAC-S12R4-A) + Free Installation Kit & 12 Months Warranty',
  'price': '₦ 321,550',
  'discount': '17%',
  'stock': 'NA'},
 {'name': 'Haier Thermocool 200 Litres Chest Freezer (HTF-200) - Silver + 3 Years Warranty',
  'price': '₦ 392,915',
  'discount': '14%',
  'stock': 'NA'},
 {'name': 'Hisense 7.5kg Twin Tub Washing Machine - (WSQB 753 (JF)',
  'price': '₦ 189,999',
  'discount': '19%',
  'stock': 'NA'},
 {'name': 'Snowsea 8kg Double Tub Washing Machine 785*465*870 MM (Machine Gross Weight 21KG)',
  'price': '₦ 190,500',
  'discount': '3%',
  'stock': 'NA'},
 {'name': 'SOLITEC 18" Standing fan plus',
  'price': '₦ 20,058',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'Syinix Swallow Maker- Fully Automatic -fufu/Eba/Yam Pounder',
  'price': '₦ 122,793',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': '5Pieces Home Light Bulb LED E27-5W-Cool White Light',
  'price': '₦ 1,799',
  'discount': '48%',
  'stock': 'NA'},
 {'name': 'ECOFLOW RIVER 2 Pro Portable Power Station, 768Wh LiFeP04 Battery, 70 Min Fast Charging, 3X800W AC Outlets,  For Outdoor Camping/RVs/Home Use',
  'price': '₦ 564,659',
  'discount': '65%',
  'stock': 'NA'},
 {'name': 'Ecoa Char Charcoal Stove',
  'price': '₦ 29,900',
  'discount': '36%',
  'stock': 'NA'},
 {'name': 'HITHIUM 1kWh Power Station - Solar charge + Power for TV/Fan/Wifi',
  'price': '₦ 292,994',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'Mythco 100 LEDs Solar Outdoor Lights With Motion Sensor 2 Pack',
  'price': '₦ 8,990',
  'discount': '36%',
  'stock': 'NA'},
 {'name': 'Ultra-Soft Fiber Pillow - 2 pieces',
  'price': '₦ 9,700',
  'discount': '35%',
  'stock': 'NA'},
 {'name': 'Hc 16 inches Solar Rechargeable Standing Fan(C168) + Solar Panel-White',
  'price': '₦ 42,532',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'DIY Wall Clock With Number Stickers - Night - 40cm',
  'price': '₦ 5,400',
  'discount': '46%',
  'stock': 'NA'},
 {'name': 'ECOFLOW RIVER 2 MAX Portable Power Station, 512Wh LiFeP04 Battery/ 1 Hour Fast Charging, Up To 1000W Output,  For Outdoor Camping/RVs/Home Use',
  'price': '₦ 477,140',
  'discount': '58%',
  'stock': 'NA'},
 {'name': 'Sun King Solar Fan With 20W Solar Panel',
  'price': '₦ 112,784',
  'discount': '17%',
  'stock': 'NA'},
 {'name': 'ECOFLOW 1024WH  1800W DELTA 2 Portable Power Station  Solar Generator For Home Backup',
  'price': '₦ 732,292',
  'discount': '79%',
  'stock': 'NA'},
 {'name': 'Plastic Hanger Set Of 12-black',
  'price': '₦ 2,699',
  'discount': '73%',
  'stock': 'NA'},
 {'name': 'Sun King Pico Plus 50 Lumens Solar Portable Emergency Lamp - Yellow',
  'price': '₦ 9,100',
  'discount': '15%',
  'stock': 'NA'},
 {'name': 'Beautiful 2pcs Kitchen Mat/Rug--H',
  'price': '₦ 5,995',
  'discount': '76%',
  'stock': 'NA'},
 {'name': 'Modern 3D Pattern Large Center Rug- 120*160cm--G',
  'price': '₦ 18,995',
  'discount': '37%',
  'stock': 'NA'},
 {'name': 'Ace Elec 20000 MAh Ultra Slim Portable Power Bank',
  'price': '₦ 7,882',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'VIC ♛20000mAh Power Banks 74Wh Portable Charger Ultra Slim Battery Pack( Type C Input)',
  'price': '₦ 7,358',
  'discount': '62%',
  'stock': 'NA'},
 {'name': 'Macbook PRO Laptop A1278 13.3 Inch Core I5 2.5GHz 8GB RAM 500GB EN/AR Keyboard',
  'price': '₦ 189,999',
  'discount': '1%',
  'stock': 'NA'},
 {'name': 'Umbrella Automatic Sunny  Anti-ultraviolet Folding Umbrella',
  'price': '₦ 9,960',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'Blueing 15.6" Laptop J4125 8GB+256GB SSD Student Portable Computer',
  'price': '₦ 231,000',
  'discount': '42%',
  'stock': 'NA'},
 {'name': 'NIVEA MEN Deep Body Lotion 400ml + Deep Roll-on 50ml',
  'price': '₦ 5,385',
  'discount': '22%',
  'stock': 'NA'},
 {'name': 'Elegant Toothbrush Holder And Automatic Toothpaste Dispenser',
  'price': '₦ 2,199',
  'discount': '76%',
  'stock': 'NA'},
 {'name': "GALUIN Trendy Versatile Shoes Men's Lightweight Casual Tide Shoes",
  'price': '₦ 14,080',
  'discount': '21%',
  'stock': 'NA'},
 {'name': 'Cotton Club AUD DE PERFUME',
  'price': '₦ 2,741',
  'discount': '9%',
  'stock': 'NA'},
 {'name': 'Ace Elec 50000 MAh Power Banks With LED Light Portable Super Fast Charger..',
  'price': '₦ 25,882',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'Haisic 20000mah Super Fast Charging Power Bank',
  'price': '₦ 10,000',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'Hc 16 inches Solar Rechargeable Standing Fan(C168) + Solar Panel-White',
  'price': '₦ 42,532',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'XIAOMI Redmi A5 6.88" 3GB RAM/64GB ROM Android 15 - Black',
  'price': '₦ 96,659',
  'discount': '2%',
  'stock': 'NA'},
 {'name': '9 In 1 Push Up Rack Board Fitness Exercise BodyBuilding Tool',
  'price': '₦ 14,340',
  'discount': '30%',
  'stock': 'NA'},
 {'name': 'Boscon Auto Ignition Table Top Gas Cooker-2 Burner-Silver',
  'price': '₦ 15,900',
  'discount': '10%',
  'stock': 'NA'},
 {'name': 'Infinix Hot 50 Pro+ 6.78" 8GB RAM/128GB ROM Android 14- Black',
  'price': '₦ 256,316',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'Tecno T101 1.8" Dual SIM  - Black',
  'price': '₦ 12,104',
  'discount': '1%',
  'stock': 'NA'},
 {'name': 'XIAOMI Redmi A5 6.88" 3GB RAM/64GB ROM Android 15 - Black',
  'price': '₦ 96,659',
  'discount': '2%',
  'stock': 'NA'},
 {'name': 'Samsung Galaxy A05 6.7" 4GB RAM/64GB ROM Android 13 - Black',
  'price': '₦ 120,577',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': "XIAOMI Redmi 14C 6.88'' 4GB RAM/128GB ROM Android 14 - Midnight Black",
  'price': '₦ 125,712',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'Samsung Galaxy A16 6.7" HD 6GB RAM/128GB ROM Android 14  - Black',
  'price': '₦ 238,959',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'XIAOMI REDMI A5 -  6.88   4GB RAM/128GB ROM  -- BLACK',
  'price': '₦ 109,450',
  'discount': '2%',
  'stock': 'NA'},
 {'name': 'Infinix Smart 10 6.7" 3GB RAM/64GB ROM Android 14',
  'price': '₦ 103,053',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'Samsung Galaxy A06 6.7" 4GB RAM/64GB ROM Android 14 - Black',
  'price': '₦ 142,688',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': "XIAOMI Redmi 14C 6.88'' 8GB RAM/256GB ROM Android 12-Midnight Black..",
  'price': '₦ 157,722',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'Infinix Hot 50i 6.78" 4GB RAM/128GB ROM Android 13- Black',
  'price': '₦ 140,632',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'XIAOMI Redmi A3 Pro 6.88" 4GB RAM / 128GB ROM Android 14 - Midnight Black',
  'price': '₦ 121,895',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': 'Samsung Galaxy A25 5G 6.5" 8GB RAM/256GB ROM Android 14 -  Light Blue',
  'price': '₦ 440,703',
  'discount': '4%',
  'stock': 'NA'},
 {'name': "itel S24 6.6'' 8GB RAM/128GB ROM Android 13 - Starry Black",
  'price': '₦ 119,993',
  'discount': '51%',
  'stock': 'NA'},
 {'name': 'Tecno Pop 9 6.67" 4GB RAM / 128GB ROM Android 14 - Black',
  'price': '₦ 132,900',
  'discount': '9%',
  'stock': 'NA'},
 {'name': 'EAGEAT Unisex Anti Blue Light Protective Computer Screen Glasses',
  'price': '₦ 2,395',
  'discount': '29%',
  'stock': 'NA'},
 {'name': 'MATIHO One-piece hair clippers',
  'price': '₦ 2,848',
  'discount': '48%',
  'stock': 'NA'},
 {'name': 'VIC ✪20000mAh Power Banks 74Wh Portable Charger Ultra Slim Battery Pack( Type C Input)',
  'price': '₦ 6,992',
  'discount': '65%',
  'stock': 'NA'},
 {'name': 'GUEETON 128GB Metal OTG Usb Flash Drive Waterproof 3D Embossment',
  'price': '₦ 5,522',
  'discount': '51%',
  'stock': 'NA'},
 {'name': 'Catpapa 0-5Years Baby Girls Long Sleeve Tees With Skirt',
  'price': '₦ 8,000',
  'discount': '62%',
  'stock': 'NA'},
 {'name': 'LZDUATAN 10 Steps Laptop Stand',
  'price': '₦ 2,845',
  'discount': '46%',
  'stock': 'NA'},
 {'name': "TOUPHY T-Shirts +Shorts 100% Cotton Men's Short Sleeve Set-White",
  'price': '₦ 7,780 - ₦ 9,600',
  'discount': '74%',
  'stock': 'NA'},
 {'name': 'Mateamoda Men Shoes Sneakers Sport Shoes Running Sneakers Casual Shoes  Welcome To Smark',
  'price': '₦ 4,470',
  'discount': '45%',
  'stock': 'NA'},
 {'name': 'Blueing 15.6" Laptop J4125 8GB+256GB SSD Student Portable Computer',
  'price': '₦ 231,000',
  'discount': '42%',
  'stock': 'NA'},
 {'name': 'Stainless Steel Octagonal Coffee Mug Portable Insulated Mug',
  'price': '₦ 6,732',
  'discount': '61%',
  'stock': 'NA'},
 {'name': 'Biore UV Aqua Rich Watery Essence Sunscreen SPF 50 (50ML)',
  'price': '₦ 3,970',
  'discount': '51%',
  'stock': 'NA'},
 {'name': 'EiFESS Artificial Flowers Wedding Party Decor (Beige Brown-6pcs)',
  'price': '₦ 5,584',
  'discount': '57%',
  'stock': 'NA'},
 {'name': 'STY Women Leopard Print Tote Bag Large Capacity Handbag - Brown',
  'price': '₦ 9,338',
  'discount': '36%',
  'stock': 'NA'},
 {'name': 'camiwind 5-in-1 Pure Cotton Printing Available T Shirts-Black',
  'price': '₦ 9,785',
  'discount': '80%',
  'stock': 'NA'},
 {'name': "2.2'' Full Touch Screen Smart Watch - For Android & IOS",
  'price': '₦ 7,725',
  'discount': '61%',
  'stock': 'NA'},
 {'name': 'Haier Thermocool 1HP Quantum Air Conditioner Energy Saving (HSU-09CFQE-QW01) - White + 3 Years Warranty & Free Kit',
  'price': '₦ 319,999',
  'discount': '22%',
  'stock': 'NA'},
 {'name': 'Century 50 Inches VIDA Smart 4K UHD TV (CTV-50) + 1 YEAR WARRANTY',
  'price': '₦ 335,000',
  'discount': '25%',
  'stock': 'NA'},
 {'name': 'Nexus 50" Inches UHD 4K VIDAA Smart Frameless TV (U4K624B)SA + 1 Year Warranty & Free Blender',
  'price': '₦ 399,999',
  'discount': '28%',
  'stock': 'NA'},
 {'name': 'Mora 43" inch LED Smart HD TV (TV 43D4N) - Black With Free Bracket',
  'price': '₦ 249,999',
  'discount': '30%',
  'stock': 'NA'},
 {'name': 'Scanfrost 8KG Twin Tub Washing Machine (SFSANTTB8)',
  'price': '₦ 239,999',
  'discount': '29%',
  'stock': 'NA'},
 {'name': 'XIAOMI Redmi Buds 6 Lite - White',
  'price': '₦ 22,828',
  'discount': '23%',
  'stock': 'NA'},
 {'name': 'LG 80W Powerful Sound, 2 Mic, Bluetooth Speaker (AUD 2S XL)',
  'price': '₦ 159,999',
  'discount': '30%',
  'stock': 'NA'},
 {'name': 'Nexus 43 Inch Smart Frameless LED TV( NX-TV43F621B)',
  'price': '₦ 259,999',
  'discount': '24%',
  'stock': 'NA'},
 {'name': 'LG 5W Powerful Bass Bluetooth Speaker (G2KB)',
  'price': '₦ 49,999',
  'discount': '21%',
  'stock': 'NA'},
 {'name': 'Ace Elec 20000MAH Power Banks Portable Super Fast Charger - 22.5W',
  'price': '₦ 7,999',
  'discount': '40%',
  'stock': 'NA'},
 {'name': 'Bruhm 1HP Split Air Conditioner (BAS-09RCEW) - White',
  'price': '₦ 299,999',
  'discount': '22%',
  'stock': 'NA'},
 {'name': 'Scanfrost 6Kg Twin Tub Washing Machine (SFWMTTA)',
  'price': '₦ 208,250',
  'discount': '17%',
  'stock': 'NA'},
 {'name': 'Polystar 30A Voltage Protection(PV-AC30AMP)',
  'price': '₦ 6,120',
  'discount': '17%',
  'stock': 'NA'},
 {'name': 'LG 250W Xboom Dynamic Pixel Lighting & Multi Colored Speaker (AUD 7S-XL)',
  'price': '₦ 389,999',
  'discount': '29%',
  'stock': 'NA'},
 {'name': 'Maxi 15L, 1500W Blender (MAXI BLE1501W)',
  'price': '₦ 95,600',
  'discount': '23%',
  'stock': 'NA'},
 {'name': 'Century 50 Inches VIDA Smart 4K UHD TV (CTV-50) + 1 YEAR WARRANTY',
  'price': '₦ 335,000',
  'discount': '25%',
  'stock': 'NA'},
 {'name': "Letv 32'' Inches Frameless HD LED TV-Black + 1 YEAR WARRANTY",
  'price': '₦ 99,000',
  'discount': '4%',
  'stock': 'NA'},
 {'name': 'Mi+ NETFLIX, Prime Video, YouTube installed MXQ pro Smart Box with MI+ 32” LED Tv',
  'price': '₦ 126,500',
  'discount': '12%',
  'stock': 'NA'},
 {'name': 'Sonivia Powerful Bluetooth Home Theater with extra bass',
  'price': '₦ 31,999',
  'discount': '10%',
  'stock': 'NA'},
 {'name': 'TCL 55 Inches UHD 4k Google Smart TV (55P635) + 1 Year Warranty',
  'price': '₦ 459,999',
  'discount': '21%',
  'stock': 'NA'},
 {'name': 'Nexus 50" Inches UHD 4K VIDAA Smart Frameless TV (U4K624B)SA + 1 Year Warranty & Free Blender',
  'price': '₦ 399,999',
  'discount': '28%',
  'stock': 'NA'},
 {'name': 'Hisense 43" Inches LED HD TV (43A5200) - Black +1 Year Warranty',
  'price': '₦ 267,800',
  'discount': '7%',
  'stock': 'NA'},
 {'name': 'Royal 43 Inches Smart TV (RTV43E5N) + 2 Years Warranty',
  'price': '₦ 259,999',
  'discount': '23%',
  'stock': 'NA'},
 {'name': 'LG 5W XBOOM Portable & Powerful Bass Speaker (AUD 2TBK)',
  'price': '₦ 44,380',
  'discount': '17%',
  'stock': 'NA'},
 {'name': 'Qsonic Bolan 900D Series.2.1 ch Surround Soundbar Home cinema with immersive Technology + BigSound Subwoofer and Upfiring inbuilt speakers S-2001 S-2001',
  'price': '₦ 89,989',
  'discount': '33%',
  'stock': 'NA'},
 {'name': 'Nexus 43 Inch Smart Frameless LED TV( NX-TV43F621B)',
  'price': '₦ 259,999',
  'discount': '24%',
  'stock': 'NA'},
 {'name': 'Royal 50 Inches 4k UHD Google TV (RTV50GT8W) + 1 Year Warranty',
  'price': '₦ 369,999',
  'discount': '23%',
  'stock': 'NA'},
 {'name': 'UFC 55 Inch 4K Ultra-HD Smart Freamless Android TV+ FREE WALL HANGER',
  'price': '₦ 368,990',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': "Cuban Chain Men's Bracelet Necklace 2-in-1 Set",
  'price': '₦ 3,325',
  'discount': '28%',
  'stock': 'NA'},
 {'name': 'Skechers  GO WALK MAX - MIDSHORE - MEN',
  'price': '₦ 70,150',
  'discount': 'NA',
  'stock': 'NA'},
 {'name': '2 Pieces  Leather Automatic Buckle Belt - Black And Golden',
  'price': '₦ 5,650',
  'discount': '40%',
  'stock': 'NA'},
 {'name': 'ASHION Martin Boots: Sleek, Durable, And Stylish Footwear For Every Occasion!',
  'price': '₦ 16,835',
  'discount': '46%',
  'stock': 'NA'},
 {'name': 'ADIDAS Core Sneakers Advantage Base',
  'price': '₦ 41,387',
  'discount': '69%',
  'stock': 'NA'},
 {'name': "10 Pairs Men's Casual Boat Unisex Sport Ankle Socks Solid Color",
  'price': '₦ 4,504',
  'discount': '44%',
  'stock': 'NA'},
 {'name': 'DS Stone Iced Men"s Wristwatch Hand Chain',
  'price': '₦ 14,990',
  'discount': '17%',
  'stock': 'NA'},
 {'name': 'Monospec Sneakers - White',
  'price': '₦ 12,980',
  'discount': '30%',
  'stock': 'NA'},
 {'name': 'Riapawel 4 PCS Bohemian Beaded Bracelets',
  'price': '₦ 2,834',
  'discount': '30%',

In [25]:
all_goods = pd.DataFrame(data)
all_goods

,name,price,discount,stock
0,"YARA Baby Diaper Size 2 Mini 3-6 Kg, Small Pac...",₦ 730,16%,19 items left
1,Ace Elec 50000 MAh Power Banks With LED Light ...,"₦ 24,882",4%,50 items left
2,6Inch LED Selfie Ring Light & Tripod Stand 2 P...,"₦ 5,590",53%,77 items left
3,"NIVEA Dry Impact Roll-on For Men, 72h- 50ml (P...","₦ 5,085",17%,46 items left
4,Roushun Vitamin C Serum [Anti-Aging Serum]---30ml,"₦ 2,399",52%,50 items left
...,...,...,...,...
279,Martell Cognac Blue Swift 75cl (VSOP),"₦ 77,034",NA,NA
280,Johnnie Walker Red Label 70cl.,"₦ 19,604",9%,NA
281,Martini Asti Spumante Sparkling Wine 75cl,"₦ 10,999",13%,NA
282,Absolut Citron Vodka 1L,"₦ 16,954",NA,NA
283,Orijin Bitters 20cl x24,"₦ 19,999",16%,NA

#### Getting some the pages in the Jumia site

In [26]:
from time import sleep

link = 'https://www.jumia.com.ng/'
url_list = ['mlp-appliances/', 'phone-tablets', 'health-beauty/', 'home-office/']
page_part1 = '?page='
page_part2 = '#catalog-listing'

data = []

for cat in url_list:
    for num in range(5):
        url = f"{link}{cat}{page_part1}{num}{page_part2}"
        response = requests.get(url)
        html_content = response.text
        soup = bs(html_content, 'lxml')
        all_page_items = soup.find_all('div', class_ = 'itm col')

        for item in all_page_items:    
            item_name = item.find('div', class_ = 'name')
            name = item_name.text if item_name else 'NA' # returns 'NA' if it doesn't exist
            
            item_price = item.find('div', class_ = 'prc')
            price = item_price.text if item_price else 'NA'
            
            item_discount = item.find('div', class_ = 'bdg _dsct')
            discount = item_discount.text if item_discount else 'NA'
            
            item_stock = item.find('div', class_ = 'stk')
            stock = item_stock.text if item_stock else 'NA'
        
            goods = {
                'name': name,
                'price': price,
                'discount': discount,
                'stock': stock
            }
        
            data.append(goods)
        sleep(2) # after each iteration, it waits for 2 secs, (after importing sleep from time)

In [22]:
jumia_pages = pd.DataFrame(data)
jumia_pages

,name,price,discount,stock
0,Oraimo Traveler 4 20000mAh 10.5W Power Bank,"₦ 13,488",55%,NA
1,TINMO 18 Inches Rechargeable Standing fan + 12...,"₦ 55,999",4%,NA
2,HANSEN 18 inches Industrial level standing fan,"₦ 18,500",5%,NA
3,Hisense 20 Litres Microwave (H20MOWS14) - Whit...,"₦ 79,999",1%,NA
4,Binatone 1.5HP Split Air Conditioner Inverter ...,"₦ 391,061",NA,NA
...,...,...,...,...
713,"ECOFLOW Solar Generator RIVER 2, 256Wh Portabl...","₦ 456,803",53%,NA
714,ECOFLOW 1800W DF Both LPG And Gas Powered Supp...,"₦ 769,999",46%,NA
715,ECOFLOW DELTA 2 & 220W Solar Panel Solar G-ene...,"₦ 899,993",18%,NA
716,ECOFLOW RIVER 3 Plus Portable Power Station – ...,"₦ 378,939",15%,NA
717,ECOFLOW 220Watt Bifacial Foldable Solar Panel,"₦ 354,200",40%,NA

### Getting all the pages in Jumia site

In [32]:
from time import sleep

link = 'https://www.jumia.com.ng/'
url_list = ['mlp-appliances/', 'phone-tablets', 'health-beauty/', 
            'home-office/', 'electronics/', 'category-fashion-by-jumia/',
            'groceries/', 'computing/', 'baby-products/', 'video-games/',

            'musical-instruments/', 'toys-games/', 'sporting-goods/',
            'mlp-official-stores/', 'automobile/', 'books-movies-music/',
            'pet-supplies/', 'seasonal-decor/', 'mlp-awoof-of-the-month/', 'mlp-official-stores/']
page_part1 = '?page='
page_part2 = '#catalog-listing'

data2 = []

for cat in url_list:
    for num in range(5):
        url = f"{link}{cat}{page_part1}{num}{page_part2}"
        response = requests.get(url)

        # Incase the page number doesnt exist
        if response.status_code == 200:
            html_content = response.text
            soup = bs(html_content, 'lxml')
            jumia_page_items = soup.find_all('div', class_ = 'itm col')
    
            for item in jumia_page_items:    
                item_name = item.find('div', class_ = 'name')
                name = item_name.text if item_name else 'NA' # returns 'NA' if it doesn't exist
                
                item_price = item.find('div', class_ = 'prc')
                price = item_price.text if item_price else 'NA'
                
                item_discount = item.find('div', class_ = 'bdg _dsct')
                discount = item_discount.text if item_discount else 'NA'
                
                item_stock = item.find('div', class_ = 'stk')
                stock = item_stock.text if item_stock else 'NA'
    
                item_img = item.find('img').get('src') # to get images and doesn't go with .text
                image = item_img if item_img else 'NA'
            
                goods = {
                    'Item Names': name,
                    'Price': price,
                    'Discount': discount,
                    'Stock': stock,
                    'Image Link': image
                }
            
                data.append(goods)
            sleep(2) # after each iteration, it waits for 2 secs, (after importing sleep from time)
        else:
            pass

In [31]:
jumia = pd.DataFrame(data2)
jumia

Empty DataFrame
Columns: []
Index: []

In [ ]:
# jumia.to_csv('jumia_ass.csv', index = False)

## Scraping JiJi site

In [76]:
jiji_url = 'http://jiji.ng/vehicles'
jiji_response = requests.get(jiji_url)
jiji_content = jiji_response.text
jiji_soup = bs(jiji_content, 'lxml')

jiji_data = []

item_collection = jiji_soup.find_all('div', class_ = 'masonry-column')

for item in item_collection:
    jiji_items = item.find_all('div', class_ = 'masonry-item')

    for good in jiji_items:
        product_name = good.find('div', class_ = 'qa-advert-title')
        name = product_name.text.strip() if product_name else 'NA'

        product_price = good.find('div', class_ = 'qa-advert-price')
        price = product_price.text.strip() if product_price else 'NA'

        product_describe = good.find('div', 'b-list-advert-base__description-text')
        description = product_describe.text.strip() if product_describe else 'NA'

        product_img = good.find('img')
        image_link = product_img.get('src') if product_img else 'NA'

        goods = {
            'Names': name,
            'Price': price,
            'Description': description,
            'Image_Link': image_link
        }
        jiji_data.append(goods)

In [77]:
jiji_data

[{'Names': 'Toyota Venza 2010 Black',
  'Price': '₦ 10,800,000',
  'Description': 'Full options v6 2010 Venza with double pano',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/178464476_MzAwLTIwOC0zZWJjYWY5NDI2.webp'},
 {'Names': 'Toyota Camry LE 4dr Sedan (2.5L 4cyl 6A) 2013 Gold',
  'Price': '₦ 14,500,000',
  'Description': 'Newly arrived Toyota Camry 2013 accident free, very clean both interior and exterior almost brand...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/158035450_MzAwLTIyNS1jM2Q0N2Y2ZDli.webp'},
 {'Names': 'Toyota Corolla 2002 White',
  'Price': '₦ 3,200,000',
  'Description': 'Super clean Toyota corolla',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/178463934_MzAwLTQwMC0zZDAxMTE4ZWQz.webp'},
 {'Names': 'Volkswagen Golf GTI 2012',
  'Price': '₦ 7,500,000',
  'Description': 'Volkswagen Golf Gti 2012 - Tokunbo\n2.0 V4 Turbo Engine. Fabric Interior. Nothing to Fix',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/173794258_MzAwLTUzMy02N2FlNmI3ZmI3.webp'},
 {'Names': 'Range Rover Velar Front Light',
  'Price': '₦ 1,600,000',
  'Description': 'Full light range Rover velar tokunbo with all range Rover part is available now with affordable...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/81534843_MzAwLTQwMC1mYmQ1ODgyMWVkLTE.webp'},
 {'Names': 'Front Bumper',
  'Price': '₦ 1,000,000',
  'Description': 'Black front bumper very',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/178464032_MzAwLTQwMC04OWFmZjlmNzEz.webp'},
 {'Names': 'Toyota Highlander V6 2006 Burgundy',
  'Price': '₦ 11,900,000',
  'Description': 'Foreign used Toyota highlander 2006 interior and exterior excellent  engine and Gear Untouched...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/178462752_MzAwLTIxNS0zZDRiYzRlNGRj.webp'},
 {'Names': 'Toyota Highlander Limited 2012 Black',
  'Price': '₦ 20,700,000',
  'Description': 'Foreign used 2012 Highlander Limited Edition with thumbstart',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/178028713_MzAwLTQwMC1lNTU0ZTc4NDY2.webp'},
 {'Names': 'Complete Lower Arm Acura RDX 2018',
  'Price': '₦ 80,000',
  'Description': 'Direct toks with guarantee',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/178464597_MzAwLTM5OC04OTdmMzY2ZmEx.webp'},
 {'Names': 'Complete Velar ENGINE Range Rover',
  'Price': '₦ 4,000,000',
  'Description': 'Complete engine for velar range Rover 2018-2021 petrol with affordable price',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/77728952_MzAwLTQwMC0yYTQwOGUxY2E5LTE.webp'},
 {'Names': 'Gear Box Range Rover Sport 2015-2018',
  'Price': '₦ 4,000,000',
  'Description': 'Range Rover gear box 2015-2018 with all range rover part is Available now',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/79331978_MzAwLTQwMC0wZDQwYzczZGYzLTE.webp'},
 {'Names': 'BMW N55 Engine 3.5',
  'Price': '₦ 2,000,000',
  'Description': 'Complete engine for BMW N55 x6 and all BMW engine parts is available now with affordable price',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/82940609_MzAwLTQwMC02YTA4YzI2NTcxLTE.webp'},
 {'Names': 'Lexus RX 350 2008 Gray',
  'Price': '₦ 9,000,000',
  'Description': 'Sharp 2008 Lexus RX350 With absolutely nothing to Fix',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/178464054_MzAwLTQwMC1lYTVkODRmNDNk.webp'},
 {'Names': 'Toyota Camry XSE FWD (2.5L 4cyl 8AM) 2018 Blue',
  'Price': '₦ 36,000,000',
  'Description': '2018 Toyota Camry – Reliable, Stylish, and Fuel-Efficient!\nKey Features:\n 2.5L 4-Cylinder Engine –...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/178219919_MzAwLTQwMC03NDk3M2Y0OTRl.webp'},
 {'Names': 'Lexus ES 350 2011 Silver',
  'Price': '₦ 15,000,000',
  'Description': 'Let’s Deal. Buy and Drive Belguim Lexus Es350 Very Affordable',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/176511133_MzAwLTQwMC0xNjI0ZTczNjZh.webp'},
 {'Names': 'Honda Accord EX-L 4dr Sedan FWD (2.4L 4cyl 2A) 2013 Silver',
  'Price': '₦ 10,300,000',
  'Description': 'Distress sale on this 2013 Honda Accord with original duty is now available for sale \nSuper clean...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/178466524_MzAwLTIyNS1kYjhiNWFlNGQz.webp'},
 {'Names': 'Turbo Range Rover Evoque',
  'Price': '₦ 250,000',
  'Description': 'Range Rover evoug turbo with all evoug part is available now with affordable price',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/78775909_MzAwLTMwMC00ZmFlNDFjNzU3LTE.webp'},
 {'Names': 'Honda Accord 1999 Black',
  'Price': '₦ 2,500,000',
  'Description': 'Honda Accord 1999 - Registered, V6, Leather interior, AC perfect, Stereo working CD/Radio,Buy &...',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/177411784_MzAwLTQwMC05MWNjNzAxMzVh.webp'},
 {'Names': 'Fan for Range Rover Evoque',
  'Price': '₦ 90,000',
  'Description': 'Range rover evoque ac fan and all range rover parts is available with affordable price',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/86466468_MzAwLTQwMC1hYjBlMjg1M2EwLTE.webp'},
 {'Names': 'Engine for Range Rover',
  'Price': '₦ 2,500,000',
  'Description': 'Range Rover engine 2010-2012 is available now with affordable price',
  'Image_Link': 'https://pictures-nigeria.jijistatic.net/89794757_MzAwLTIyNS04MDMwMzczNWY0LTE.webp'}]

In [85]:
df = pd.DataFrame(jiji_data)
df.head()

,Names,Price,Description,Image_Link
0,Toyota Venza 2010 Black,"₦ 10,800,000",Full options v6 2010 Venza with double pano,https://pictures-nigeria.jijistatic.net/178464...
1,Toyota Camry LE 4dr Sedan (2.5L 4cyl 6A) 2013 ...,"₦ 14,500,000","Newly arrived Toyota Camry 2013 accident free,...",https://pictures-nigeria.jijistatic.net/158035...
2,Toyota Corolla 2002 White,"₦ 3,200,000",Super clean Toyota corolla,https://pictures-nigeria.jijistatic.net/178463...
3,Volkswagen Golf GTI 2012,"₦ 7,500,000",Volkswagen Golf Gti 2012 - Tokunbo\n2.0 V4 Tur...,https://pictures-nigeria.jijistatic.net/173794...
4,Range Rover Velar Front Light,"₦ 1,600,000",Full light range Rover velar tokunbo with all ...,https://pictures-nigeria.jijistatic.net/815348...

In [86]:
# Extracting the Brand Name and storing in a column
df['Brand'] = df['Names'].apply(lambda x : str(x).split(' ')[0])
df.head()

,Names,Price,Description,Image_Link,Brand
0,Toyota Venza 2010 Black,"₦ 10,800,000",Full options v6 2010 Venza with double pano,https://pictures-nigeria.jijistatic.net/178464...,Toyota
1,Toyota Camry LE 4dr Sedan (2.5L 4cyl 6A) 2013 ...,"₦ 14,500,000","Newly arrived Toyota Camry 2013 accident free,...",https://pictures-nigeria.jijistatic.net/158035...,Toyota
2,Toyota Corolla 2002 White,"₦ 3,200,000",Super clean Toyota corolla,https://pictures-nigeria.jijistatic.net/178463...,Toyota
3,Volkswagen Golf GTI 2012,"₦ 7,500,000",Volkswagen Golf Gti 2012 - Tokunbo\n2.0 V4 Tur...,https://pictures-nigeria.jijistatic.net/173794...,Volkswagen
4,Range Rover Velar Front Light,"₦ 1,600,000",Full light range Rover velar tokunbo with all ...,https://pictures-nigeria.jijistatic.net/815348...,Range

In [87]:
# Formatting the price to be mathematically operational
def clean(text):
    return text.replace(' ', '').replace('₦', '').replace(',', '')


df['Selling_Price'] = df['Price'].apply(lambda x: float(clean(str(x))) + 500000)  
# We cleaned the value and added 500,000 to the price and converted to float
df.head(10)

,Names,Price,Description,Image_Link,Brand,Selling_Price
0,Toyota Venza 2010 Black,"₦ 10,800,000",Full options v6 2010 Venza with double pano,https://pictures-nigeria.jijistatic.net/178464...,Toyota,11300000.0
1,Toyota Camry LE 4dr Sedan (2.5L 4cyl 6A) 2013 ...,"₦ 14,500,000","Newly arrived Toyota Camry 2013 accident free,...",https://pictures-nigeria.jijistatic.net/158035...,Toyota,15000000.0
2,Toyota Corolla 2002 White,"₦ 3,200,000",Super clean Toyota corolla,https://pictures-nigeria.jijistatic.net/178463...,Toyota,3700000.0
3,Volkswagen Golf GTI 2012,"₦ 7,500,000",Volkswagen Golf Gti 2012 - Tokunbo\n2.0 V4 Tur...,https://pictures-nigeria.jijistatic.net/173794...,Volkswagen,8000000.0
4,Range Rover Velar Front Light,"₦ 1,600,000",Full light range Rover velar tokunbo with all ...,https://pictures-nigeria.jijistatic.net/815348...,Range,2100000.0
5,Front Bumper,"₦ 1,000,000",Black front bumper very,https://pictures-nigeria.jijistatic.net/178464...,Front,1500000.0
6,Toyota Highlander V6 2006 Burgundy,"₦ 11,900,000",Foreign used Toyota highlander 2006 interior a...,https://pictures-nigeria.jijistatic.net/178462...,Toyota,12400000.0
7,Toyota Highlander Limited 2012 Black,"₦ 20,700,000",Foreign used 2012 Highlander Limited Edition w...,https://pictures-nigeria.jijistatic.net/178028...,Toyota,21200000.0
8,Complete Lower Arm Acura RDX 2018,"₦ 80,000",Direct toks with guarantee,https://pictures-nigeria.jijistatic.net/178464...,Complete,580000.0
9,Complete Velar ENGINE Range Rover,"₦ 4,000,000",Complete engine for velar range Rover 2018-202...,https://pictures-nigeria.jijistatic.net/777289...,Complete,4500000.0

In [88]:
df.to_excel('jiji_data.xlsx', index = False)